version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:10"
      timezone: Europe/Paris
    open-pull-requests-limit: 5
    labels: [dependencies, github-actions]
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:20"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels: [dependencies, javascript]
    groups:
      production-dependencies:
        dependency-type: production
      development-dependencies:
        dependency-type: development

  - package-ecosystem: gomod
    directory: /cli
    schedule:
      interval: weekly
      day: monday
      time: "05:30"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    labels: [dependencies, go]
    groups:
      go-modules:
        patterns: ["*"]
