version: 2
project_name: towk

builds:
  - id: towk-cli
    binary: chatto
    env:
      - CGO_ENABLED=0
    dir: ./cli
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - formats: [tar.gz]
    files:
      - LICENSES/AGPL-3.0-or-later.txt
      - NOTICE
      - SOURCE.md
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "freebsd" }}FreeBSD{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  github:
    owner: Yo-DDV
    name: towk
  draft: true
  use_existing_draft: true
  replace_existing_artifacts: true
  mode: keep-existing
  prerelease: auto
