version: 2
project_name: towk

builds:
  - id: towk-cli
    binary: towk
    mod_timestamp: "946684800"
    env:
      - CGO_ENABLED=0
    dir: ./cli
    goos:
      - linux
      - freebsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - ids: [towk-cli]
    formats: [tar.gz]
    builds_info:
      owner: root
      group: root
      mode: 0755
      mtime: "2000-01-01T00:00:00Z"
    files:
      - src: LICENSE
        info: &legal_file_info
          owner: root
          group: root
          mode: 0644
          mtime: "2000-01-01T00:00:00Z"
      - src: LICENSES/AGPL-3.0-or-later.txt
        info: *legal_file_info
      - src: LICENSES/Apache-2.0.txt
        info: *legal_file_info
      - src: LICENSING.md
        info: *legal_file_info
      - src: NOTICE
        info: *legal_file_info
      - src: REUSE.toml
        info: *legal_file_info
      - src: SOURCE.md
        info: *legal_file_info
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "freebsd" }}FreeBSD{{ else }}{{ title .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: checksums.txt

changelog:
  disable: true

release:
  disable: true
