// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/admin/v1/diagnostics.proto

package adminv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/admin/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AdminDiagnosticsServiceName is the fully-qualified name of the AdminDiagnosticsService service.
	AdminDiagnosticsServiceName = "chatto.admin.v1.AdminDiagnosticsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AdminDiagnosticsServiceGetSystemInfoProcedure is the fully-qualified name of the
	// AdminDiagnosticsService's GetSystemInfo RPC.
	AdminDiagnosticsServiceGetSystemInfoProcedure = "/chatto.admin.v1.AdminDiagnosticsService/GetSystemInfo"
	// AdminDiagnosticsServiceGetPerformanceSettingsProcedure is the fully-qualified name of the
	// AdminDiagnosticsService's GetPerformanceSettings RPC.
	AdminDiagnosticsServiceGetPerformanceSettingsProcedure = "/chatto.admin.v1.AdminDiagnosticsService/GetPerformanceSettings"
	// AdminDiagnosticsServiceUpdatePerformanceSettingsProcedure is the fully-qualified name of the
	// AdminDiagnosticsService's UpdatePerformanceSettings RPC.
	AdminDiagnosticsServiceUpdatePerformanceSettingsProcedure = "/chatto.admin.v1.AdminDiagnosticsService/UpdatePerformanceSettings"
)

// AdminDiagnosticsServiceClient is a client for the chatto.admin.v1.AdminDiagnosticsService
// service.
type AdminDiagnosticsServiceClient interface {
	// Returns broker, JetStream, and projection diagnostics. Requires the
	// server owner role.
	GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error)
	// Returns requested and effective runtime limits. Requires owner.
	GetPerformanceSettings(context.Context, *connect.Request[v1.GetPerformanceSettingsRequest]) (*connect.Response[v1.GetPerformanceSettingsResponse], error)
	// Changes the owner-requested policy with optimistic concurrency. Requires owner.
	UpdatePerformanceSettings(context.Context, *connect.Request[v1.UpdatePerformanceSettingsRequest]) (*connect.Response[v1.UpdatePerformanceSettingsResponse], error)
}

// NewAdminDiagnosticsServiceClient constructs a client for the
// chatto.admin.v1.AdminDiagnosticsService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAdminDiagnosticsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AdminDiagnosticsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	adminDiagnosticsServiceMethods := v1.File_chatto_admin_v1_diagnostics_proto.Services().ByName("AdminDiagnosticsService").Methods()
	return &adminDiagnosticsServiceClient{
		getSystemInfo: connect.NewClient[v1.GetSystemInfoRequest, v1.GetSystemInfoResponse](
			httpClient,
			baseURL+AdminDiagnosticsServiceGetSystemInfoProcedure,
			connect.WithSchema(adminDiagnosticsServiceMethods.ByName("GetSystemInfo")),
			connect.WithClientOptions(opts...),
		),
		getPerformanceSettings: connect.NewClient[v1.GetPerformanceSettingsRequest, v1.GetPerformanceSettingsResponse](
			httpClient,
			baseURL+AdminDiagnosticsServiceGetPerformanceSettingsProcedure,
			connect.WithSchema(adminDiagnosticsServiceMethods.ByName("GetPerformanceSettings")),
			connect.WithClientOptions(opts...),
		),
		updatePerformanceSettings: connect.NewClient[v1.UpdatePerformanceSettingsRequest, v1.UpdatePerformanceSettingsResponse](
			httpClient,
			baseURL+AdminDiagnosticsServiceUpdatePerformanceSettingsProcedure,
			connect.WithSchema(adminDiagnosticsServiceMethods.ByName("UpdatePerformanceSettings")),
			connect.WithClientOptions(opts...),
		),
	}
}

// adminDiagnosticsServiceClient implements AdminDiagnosticsServiceClient.
type adminDiagnosticsServiceClient struct {
	getSystemInfo             *connect.Client[v1.GetSystemInfoRequest, v1.GetSystemInfoResponse]
	getPerformanceSettings    *connect.Client[v1.GetPerformanceSettingsRequest, v1.GetPerformanceSettingsResponse]
	updatePerformanceSettings *connect.Client[v1.UpdatePerformanceSettingsRequest, v1.UpdatePerformanceSettingsResponse]
}

// GetSystemInfo calls chatto.admin.v1.AdminDiagnosticsService.GetSystemInfo.
func (c *adminDiagnosticsServiceClient) GetSystemInfo(ctx context.Context, req *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error) {
	return c.getSystemInfo.CallUnary(ctx, req)
}

// GetPerformanceSettings calls chatto.admin.v1.AdminDiagnosticsService.GetPerformanceSettings.
func (c *adminDiagnosticsServiceClient) GetPerformanceSettings(ctx context.Context, req *connect.Request[v1.GetPerformanceSettingsRequest]) (*connect.Response[v1.GetPerformanceSettingsResponse], error) {
	return c.getPerformanceSettings.CallUnary(ctx, req)
}

// UpdatePerformanceSettings calls
// chatto.admin.v1.AdminDiagnosticsService.UpdatePerformanceSettings.
func (c *adminDiagnosticsServiceClient) UpdatePerformanceSettings(ctx context.Context, req *connect.Request[v1.UpdatePerformanceSettingsRequest]) (*connect.Response[v1.UpdatePerformanceSettingsResponse], error) {
	return c.updatePerformanceSettings.CallUnary(ctx, req)
}

// AdminDiagnosticsServiceHandler is an implementation of the
// chatto.admin.v1.AdminDiagnosticsService service.
type AdminDiagnosticsServiceHandler interface {
	// Returns broker, JetStream, and projection diagnostics. Requires the
	// server owner role.
	GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error)
	// Returns requested and effective runtime limits. Requires owner.
	GetPerformanceSettings(context.Context, *connect.Request[v1.GetPerformanceSettingsRequest]) (*connect.Response[v1.GetPerformanceSettingsResponse], error)
	// Changes the owner-requested policy with optimistic concurrency. Requires owner.
	UpdatePerformanceSettings(context.Context, *connect.Request[v1.UpdatePerformanceSettingsRequest]) (*connect.Response[v1.UpdatePerformanceSettingsResponse], error)
}

// NewAdminDiagnosticsServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAdminDiagnosticsServiceHandler(svc AdminDiagnosticsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	adminDiagnosticsServiceMethods := v1.File_chatto_admin_v1_diagnostics_proto.Services().ByName("AdminDiagnosticsService").Methods()
	adminDiagnosticsServiceGetSystemInfoHandler := connect.NewUnaryHandler(
		AdminDiagnosticsServiceGetSystemInfoProcedure,
		svc.GetSystemInfo,
		connect.WithSchema(adminDiagnosticsServiceMethods.ByName("GetSystemInfo")),
		connect.WithHandlerOptions(opts...),
	)
	adminDiagnosticsServiceGetPerformanceSettingsHandler := connect.NewUnaryHandler(
		AdminDiagnosticsServiceGetPerformanceSettingsProcedure,
		svc.GetPerformanceSettings,
		connect.WithSchema(adminDiagnosticsServiceMethods.ByName("GetPerformanceSettings")),
		connect.WithHandlerOptions(opts...),
	)
	adminDiagnosticsServiceUpdatePerformanceSettingsHandler := connect.NewUnaryHandler(
		AdminDiagnosticsServiceUpdatePerformanceSettingsProcedure,
		svc.UpdatePerformanceSettings,
		connect.WithSchema(adminDiagnosticsServiceMethods.ByName("UpdatePerformanceSettings")),
		connect.WithHandlerOptions(opts...),
	)
	return "/chatto.admin.v1.AdminDiagnosticsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AdminDiagnosticsServiceGetSystemInfoProcedure:
			adminDiagnosticsServiceGetSystemInfoHandler.ServeHTTP(w, r)
		case AdminDiagnosticsServiceGetPerformanceSettingsProcedure:
			adminDiagnosticsServiceGetPerformanceSettingsHandler.ServeHTTP(w, r)
		case AdminDiagnosticsServiceUpdatePerformanceSettingsProcedure:
			adminDiagnosticsServiceUpdatePerformanceSettingsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAdminDiagnosticsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAdminDiagnosticsServiceHandler struct{}

func (UnimplementedAdminDiagnosticsServiceHandler) GetSystemInfo(context.Context, *connect.Request[v1.GetSystemInfoRequest]) (*connect.Response[v1.GetSystemInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminDiagnosticsService.GetSystemInfo is not implemented"))
}

func (UnimplementedAdminDiagnosticsServiceHandler) GetPerformanceSettings(context.Context, *connect.Request[v1.GetPerformanceSettingsRequest]) (*connect.Response[v1.GetPerformanceSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminDiagnosticsService.GetPerformanceSettings is not implemented"))
}

func (UnimplementedAdminDiagnosticsServiceHandler) UpdatePerformanceSettings(context.Context, *connect.Request[v1.UpdatePerformanceSettingsRequest]) (*connect.Response[v1.UpdatePerformanceSettingsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.admin.v1.AdminDiagnosticsService.UpdatePerformanceSettings is not implemented"))
}
