// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"
// @generated from file chatto/api/v1/presence.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/api/v1/presence.proto.
 */
export const file_chatto_api_v1_presence: GenFile = /*@__PURE__*/
  fileDesc("ChxjaGF0dG8vYXBpL3YxL3ByZXNlbmNlLnByb3RvEg1jaGF0dG8uYXBpLnYxIvMBChVVcGRhdGVQcmVzZW5jZVJlcXVlc3QSOQoGc3RhdHVzGAEgASgOMh0uY2hhdHRvLmFwaS52MS5QcmVzZW5jZVN0YXR1c0IKukgHggEEEAEgABIVCg11c2VyX3NlbGVjdGVkGAIgASgIEiAKD2luc3RhbGxhdGlvbl9pZBgDIAEoCUIHukgEcgIYYBIbCgpzZXNzaW9uX2lkGAQgASgJQge6SARyAhhgEg4KBmFjdGl2ZRgFIAEoCBIbChNtZWFuaW5nZnVsX2FjdGl2aXR5GAYgASgIEhwKFHJlbGVhc2VfaW5zdGFsbGF0aW9uGAcgASgIIkcKFlVwZGF0ZVByZXNlbmNlUmVzcG9uc2USLQoGc3RhdHVzGAEgASgOMh0uY2hhdHRvLmFwaS52MS5QcmVzZW5jZVN0YXR1cyqoAQoOUHJlc2VuY2VTdGF0dXMSHwobUFJFU0VOQ0VfU1RBVFVTX1VOU1BFQ0lGSUVEEAASGgoWUFJFU0VOQ0VfU1RBVFVTX09OTElORRABEhgKFFBSRVNFTkNFX1NUQVRVU19BV0FZEAISIgoeUFJFU0VOQ0VfU1RBVFVTX0RPX05PVF9ESVNUVVJCEAMSGwoXUFJFU0VOQ0VfU1RBVFVTX09GRkxJTkUQBEKpAQoRY29tLmNoYXR0by5hcGkudjFCDVByZXNlbmNlUHJvdG9QAVovaG1hbnMuZGUvY2hhdHRvL2ludGVybmFsL3BiL2NoYXR0by9hcGkvdjE7YXBpdjGiAgNDQViqAg1DaGF0dG8uQXBpLlYxygINQ2hhdHRvXEFwaVxWMeICGUNoYXR0b1xBcGlcVjFcR1BCTWV0YWRhdGHqAg9DaGF0dG86OkFwaTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * Request to update the current user's live presence status.
 *
 * @generated from message chatto.api.v1.UpdatePresenceRequest
 */
export type UpdatePresenceRequest = Message<"chatto.api.v1.UpdatePresenceRequest"> & {
  /**
   * Live status requested for the authenticated user. Offline is accepted only
   * for an installation-scoped release.
   *
   * @generated from field: chatto.api.v1.PresenceStatus status = 1;
   */
  status: PresenceStatus;

  /**
   * True when this update comes from a deliberate user selection rather than
   * automatic idle/refresh updates. Automatic updates do not overwrite an
   * active manually selected Away or Do Not Disturb status from another client.
   *
   * @generated from field: bool user_selected = 2;
   */
  userSelected: boolean;

  /**
   * Stable browser-installation identifier shared with push and realtime state.
   * New clients send it with every session-aware report.
   *
   * @generated from field: string installation_id = 3;
   */
  installationId: string;

  /**
   * Opaque page-lifetime identifier. Multiple tabs from one installation own
   * independent leases so one tab cannot incorrectly hide another active tab.
   *
   * @generated from field: string session_id = 4;
   */
  sessionId: string;

  /**
   * Whether this exact page is currently active after lifecycle grace periods.
   *
   * @generated from field: bool active = 5;
   */
  active: boolean;

  /**
   * True only for foreground/resume or direct user interaction. Routine lease
   * refreshes leave this false and cannot advance profile latest activity.
   *
   * @generated from field: bool meaningful_activity = 6;
   */
  meaningfulActivity: boolean;

  /**
   * Withdraw every session lease owned by installation_id. This is used by
   * "Look offline" and requires status Offline with an empty session_id.
   *
   * @generated from field: bool release_installation = 7;
   */
  releaseInstallation: boolean;
};

/**
 * Describes the message chatto.api.v1.UpdatePresenceRequest.
 * Use `create(UpdatePresenceRequestSchema)` to create a new message.
 */
export const UpdatePresenceRequestSchema: GenMessage<UpdatePresenceRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_presence, 0);

/**
 * Result of updating live presence.
 *
 * @generated from message chatto.api.v1.UpdatePresenceResponse
 */
export type UpdatePresenceResponse = Message<"chatto.api.v1.UpdatePresenceResponse"> & {
  /**
   * Effective user-level status after aggregating all current installations.
   *
   * @generated from field: chatto.api.v1.PresenceStatus status = 1;
   */
  status: PresenceStatus;
};

/**
 * Describes the message chatto.api.v1.UpdatePresenceResponse.
 * Use `create(UpdatePresenceResponseSchema)` to create a new message.
 */
export const UpdatePresenceResponseSchema: GenMessage<UpdatePresenceResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_presence, 1);

/**
 * Live presence status returned by public read APIs.
 *
 * Offline remains a read-side state for ordinary reports. Session-aware clients
 * may send Offline only together with release_installation to withdraw this
 * browser installation's ephemeral presence leases.
 *
 * @generated from enum chatto.api.v1.PresenceStatus
 */
export enum PresenceStatus {
  /**
   * No presence status was specified.
   *
   * @generated from enum value: PRESENCE_STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The user is actively available.
   *
   * @generated from enum value: PRESENCE_STATUS_ONLINE = 1;
   */
  ONLINE = 1,

  /**
   * The user is connected but away or idle.
   *
   * @generated from enum value: PRESENCE_STATUS_AWAY = 2;
   */
  AWAY = 2,

  /**
   * The user does not want notifications while this live status is active.
   *
   * @generated from enum value: PRESENCE_STATUS_DO_NOT_DISTURB = 3;
   */
  DO_NOT_DISTURB = 3,

  /**
   * The user has no active live presence record.
   *
   * @generated from enum value: PRESENCE_STATUS_OFFLINE = 4;
   */
  OFFLINE = 4,
}

/**
 * Describes the enum chatto.api.v1.PresenceStatus.
 */
export const PresenceStatusSchema: GenEnum<PresenceStatus> = /*@__PURE__*/
  enumDesc(file_chatto_api_v1_presence, 0);
