// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file chatto/api/v1/push_notifications.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/api/v1/push_notifications.proto.
 */
export const file_chatto_api_v1_push_notifications: GenFile = /*@__PURE__*/
  fileDesc("CiZjaGF0dG8vYXBpL3YxL3B1c2hfbm90aWZpY2F0aW9ucy5wcm90bxINY2hhdHRvLmFwaS52MSK3AgoUU3Vic2NyaWJlUHVzaFJlcXVlc3QSHAoIZW5kcG9pbnQYASABKAlCCrpIB3IFEAEYgCASGgoGcDI1NmRoGAIgASgJQgq6SAdyBRABGIACEhgKBGF1dGgYAyABKAlCCrpIB3IFEAEYgAESIQoKdXNlcl9hZ2VudBgEIAEoCUIIukgFcgMYgARIAIgBARIcCgZsb2NhbGUYBSABKAlCB7pIBHICGBBIAYgBARIgCgljbGllbnRfaWQYBiABKAlCCLpIBXIDGIABSAKIAQESKQoSYXBwbGljYXRpb25fb3JpZ2luGAcgASgJQgi6SAVyAxiABEgDiAEBQg0KC191c2VyX2FnZW50QgkKB19sb2NhbGVCDAoKX2NsaWVudF9pZEIVChNfYXBwbGljYXRpb25fb3JpZ2luIisKFVN1YnNjcmliZVB1c2hSZXNwb25zZRISCgpzdWJzY3JpYmVkGAEgASgIIjYKFlVuc3Vic2NyaWJlUHVzaFJlcXVlc3QSHAoIZW5kcG9pbnQYASABKAlCCrpIB3IFEAEYgCAiLwoXVW5zdWJzY3JpYmVQdXNoUmVzcG9uc2USFAoMdW5zdWJzY3JpYmVkGAEgASgIMs8BChdQdXNoTm90aWZpY2F0aW9uU2VydmljZRJWCglTdWJzY3JpYmUSIy5jaGF0dG8uYXBpLnYxLlN1YnNjcmliZVB1c2hSZXF1ZXN0GiQuY2hhdHRvLmFwaS52MS5TdWJzY3JpYmVQdXNoUmVzcG9uc2USXAoLVW5zdWJzY3JpYmUSJS5jaGF0dG8uYXBpLnYxLlVuc3Vic2NyaWJlUHVzaFJlcXVlc3QaJi5jaGF0dG8uYXBpLnYxLlVuc3Vic2NyaWJlUHVzaFJlc3BvbnNlQrIBChFjb20uY2hhdHRvLmFwaS52MUIWUHVzaE5vdGlmaWNhdGlvbnNQcm90b1ABWi9obWFucy5kZS9jaGF0dG8vaW50ZXJuYWwvcGIvY2hhdHRvL2FwaS92MTthcGl2MaICA0NBWKoCDUNoYXR0by5BcGkuVjHKAg1DaGF0dG9cQXBpXFYx4gIZQ2hhdHRvXEFwaVxWMVxHUEJNZXRhZGF0YeoCD0NoYXR0bzo6QXBpOjpWMWIGcHJvdG8z", [file_buf_validate_validate]);

/**
 * Request to store a PushSubscription returned by the browser Push API.
 *
 * @generated from message chatto.api.v1.SubscribePushRequest
 */
export type SubscribePushRequest = Message<"chatto.api.v1.SubscribePushRequest"> & {
  /**
   * Push service endpoint URL.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;

  /**
   * Client P-256 ECDH public key from PushSubscription.keys.p256dh.
   *
   * @generated from field: string p256dh = 2;
   */
  p256dh: string;

  /**
   * Authentication secret from PushSubscription.keys.auth.
   *
   * @generated from field: string auth = 3;
   */
  auth: string;

  /**
   * Optional browser user-agent string for device identification.
   *
   * @generated from field: optional string user_agent = 4;
   */
  userAgent?: string | undefined;

  /**
   * Optional Towk UI language selected by this browser. The server normalizes
   * unsupported and legacy-empty values to English.
   *
   * @generated from field: optional string locale = 5;
   */
  locale?: string | undefined;

  /**
   * Stable Towk browser-installation identifier. It lets the server replace a
   * superseded endpoint for this installation without collapsing real devices.
   *
   * @generated from field: optional string client_id = 6;
   */
  clientId?: string | undefined;

  /**
   * Origin that registered the browser subscription. Used for diagnostics and
   * safe lifecycle cleanup across installed web app context refreshes.
   *
   * @generated from field: optional string application_origin = 7;
   */
  applicationOrigin?: string | undefined;
};

/**
 * Describes the message chatto.api.v1.SubscribePushRequest.
 * Use `create(SubscribePushRequestSchema)` to create a new message.
 */
export const SubscribePushRequestSchema: GenMessage<SubscribePushRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_push_notifications, 0);

/**
 * Response from storing a browser push subscription.
 *
 * @generated from message chatto.api.v1.SubscribePushResponse
 */
export type SubscribePushResponse = Message<"chatto.api.v1.SubscribePushResponse"> & {
  /**
   * True when the subscription was stored.
   *
   * @generated from field: bool subscribed = 1;
   */
  subscribed: boolean;
};

/**
 * Describes the message chatto.api.v1.SubscribePushResponse.
 * Use `create(SubscribePushResponseSchema)` to create a new message.
 */
export const SubscribePushResponseSchema: GenMessage<SubscribePushResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_push_notifications, 1);

/**
 * Request to remove a browser push subscription.
 *
 * @generated from message chatto.api.v1.UnsubscribePushRequest
 */
export type UnsubscribePushRequest = Message<"chatto.api.v1.UnsubscribePushRequest"> & {
  /**
   * Push service endpoint URL to remove.
   *
   * @generated from field: string endpoint = 1;
   */
  endpoint: string;
};

/**
 * Describes the message chatto.api.v1.UnsubscribePushRequest.
 * Use `create(UnsubscribePushRequestSchema)` to create a new message.
 */
export const UnsubscribePushRequestSchema: GenMessage<UnsubscribePushRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_push_notifications, 2);

/**
 * Response from removing a browser push subscription.
 *
 * @generated from message chatto.api.v1.UnsubscribePushResponse
 */
export type UnsubscribePushResponse = Message<"chatto.api.v1.UnsubscribePushResponse"> & {
  /**
   * True when the request completed.
   *
   * @generated from field: bool unsubscribed = 1;
   */
  unsubscribed: boolean;
};

/**
 * Describes the message chatto.api.v1.UnsubscribePushResponse.
 * Use `create(UnsubscribePushResponseSchema)` to create a new message.
 */
export const UnsubscribePushResponseSchema: GenMessage<UnsubscribePushResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_push_notifications, 3);

/**
 * Browser Web Push subscription commands for the current user.
 *
 * @generated from service chatto.api.v1.PushNotificationService
 */
export const PushNotificationService: GenService<{
  /**
   * Stores or updates the caller's browser push subscription.
   *
   * The server must have Web Push configured. Clients normally call this after
   * the browser grants notification permission and returns a PushSubscription.
   *
   * @generated from rpc chatto.api.v1.PushNotificationService.Subscribe
   */
  subscribe: {
    methodKind: "unary";
    input: typeof SubscribePushRequestSchema;
    output: typeof SubscribePushResponseSchema;
  },
  /**
   * Removes the caller's browser push subscription by endpoint.
   *
   * The call is idempotent: removing an unknown endpoint still succeeds.
   *
   * @generated from rpc chatto.api.v1.PushNotificationService.Unsubscribe
   */
  unsubscribe: {
    methodKind: "unary";
    input: typeof UnsubscribePushRequestSchema;
    output: typeof UnsubscribePushResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chatto_api_v1_push_notifications, 0);
