// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=js"
// @generated from file chatto/api/v1/roles.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/api/v1/roles.proto.
 */
export const file_chatto_api_v1_roles: GenFile = /*@__PURE__*/
  fileDesc("ChljaGF0dG8vYXBpL3YxL3JvbGVzLnByb3RvEg1jaGF0dG8uYXBpLnYxIoUBCgRSb2xlEgwKBG5hbWUYASABKAkSFAoMZGlzcGxheV9uYW1lGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhEKCWlzX3N5c3RlbRgEIAEoCBIQCghwb3NpdGlvbhgFIAEoBRIQCghwaW5nYWJsZRgGIAEoCBINCgVjb2xvchgHIAEoCSISChBMaXN0Um9sZXNSZXF1ZXN0IjcKEUxpc3RSb2xlc1Jlc3BvbnNlEiIKBXJvbGVzGAEgAygLMhMuY2hhdHRvLmFwaS52MS5Sb2xlIicKDkdldFJvbGVSZXF1ZXN0EhUKBG5hbWUYASABKAlCB7pIBHICEAEiNAoPR2V0Um9sZVJlc3BvbnNlEiEKBHJvbGUYASABKAsyEy5jaGF0dG8uYXBpLnYxLlJvbGUiNwoUQmF0Y2hHZXRSb2xlc1JlcXVlc3QSHwoFbmFtZXMYASADKAlCELpIDZIBCggBEGQiBHICEAEiOwoVQmF0Y2hHZXRSb2xlc1Jlc3BvbnNlEiIKBXJvbGVzGAEgAygLMhMuY2hhdHRvLmFwaS52MS5Sb2xlMoMCCgtSb2xlU2VydmljZRJOCglMaXN0Um9sZXMSHy5jaGF0dG8uYXBpLnYxLkxpc3RSb2xlc1JlcXVlc3QaIC5jaGF0dG8uYXBpLnYxLkxpc3RSb2xlc1Jlc3BvbnNlEkgKB0dldFJvbGUSHS5jaGF0dG8uYXBpLnYxLkdldFJvbGVSZXF1ZXN0Gh4uY2hhdHRvLmFwaS52MS5HZXRSb2xlUmVzcG9uc2USWgoNQmF0Y2hHZXRSb2xlcxIjLmNoYXR0by5hcGkudjEuQmF0Y2hHZXRSb2xlc1JlcXVlc3QaJC5jaGF0dG8uYXBpLnYxLkJhdGNoR2V0Um9sZXNSZXNwb25zZUKmAQoRY29tLmNoYXR0by5hcGkudjFCClJvbGVzUHJvdG9QAVovaG1hbnMuZGUvY2hhdHRvL2ludGVybmFsL3BiL2NoYXR0by9hcGkvdjE7YXBpdjGiAgNDQViqAg1DaGF0dG8uQXBpLlYxygINQ2hhdHRvXEFwaVxWMeICGUNoYXR0b1xBcGlcVjFcR1BCTWV0YWRhdGHqAg9DaGF0dG86OkFwaTo6VjFiBnByb3RvMw", [file_buf_validate_validate]);

/**
 * Public role metadata used for rendering role mentions, labels, and catalogs.
 *
 * @generated from message chatto.api.v1.Role
 */
export type Role = Message<"chatto.api.v1.Role"> & {
  /**
   * Stable role name used in permission and assignment records.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Display name shown in user-facing role UIs.
   *
   * @generated from field: string display_name = 2;
   */
  displayName: string;

  /**
   * Optional role description.
   *
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * Whether this is a built-in role.
   *
   * @generated from field: bool is_system = 4;
   */
  isSystem: boolean;

  /**
   * Display/order position.
   *
   * @generated from field: int32 position = 5;
   */
  position: number;

  /**
   * Whether messages may notify users assigned to this role.
   *
   * @generated from field: bool pingable = 6;
   */
  pingable: boolean;

  /**
   * Display-only accent color in canonical #RRGGBB form. Empty means the
   * ordinary text color (used by the implicit everyone role).
   *
   * @generated from field: string color = 7;
   */
  color: string;
};

/**
 * Describes the message chatto.api.v1.Role.
 * Use `create(RoleSchema)` to create a new message.
 */
export const RoleSchema: GenMessage<Role> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 0);

/**
 * Request the current role catalog.
 *
 * @generated from message chatto.api.v1.ListRolesRequest
 */
export type ListRolesRequest = Message<"chatto.api.v1.ListRolesRequest"> & {
};

/**
 * Describes the message chatto.api.v1.ListRolesRequest.
 * Use `create(ListRolesRequestSchema)` to create a new message.
 */
export const ListRolesRequestSchema: GenMessage<ListRolesRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 1);

/**
 * Snapshot of the role catalog visible to the authenticated viewer.
 *
 * @generated from message chatto.api.v1.ListRolesResponse
 */
export type ListRolesResponse = Message<"chatto.api.v1.ListRolesResponse"> & {
  /**
   * Roles sorted by position.
   *
   * @generated from field: repeated chatto.api.v1.Role roles = 1;
   */
  roles: Role[];
};

/**
 * Describes the message chatto.api.v1.ListRolesResponse.
 * Use `create(ListRolesResponseSchema)` to create a new message.
 */
export const ListRolesResponseSchema: GenMessage<ListRolesResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 2);

/**
 * Request one public role by stable role name.
 *
 * @generated from message chatto.api.v1.GetRoleRequest
 */
export type GetRoleRequest = Message<"chatto.api.v1.GetRoleRequest"> & {
  /**
   * Required stable role name.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message chatto.api.v1.GetRoleRequest.
 * Use `create(GetRoleRequestSchema)` to create a new message.
 */
export const GetRoleRequestSchema: GenMessage<GetRoleRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 3);

/**
 * Public role lookup response.
 *
 * @generated from message chatto.api.v1.GetRoleResponse
 */
export type GetRoleResponse = Message<"chatto.api.v1.GetRoleResponse"> & {
  /**
   * Requested role.
   *
   * @generated from field: chatto.api.v1.Role role = 1;
   */
  role?: Role | undefined;
};

/**
 * Describes the message chatto.api.v1.GetRoleResponse.
 * Use `create(GetRoleResponseSchema)` to create a new message.
 */
export const GetRoleResponseSchema: GenMessage<GetRoleResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 4);

/**
 * Request public role records for a set of stable role names.
 *
 * @generated from message chatto.api.v1.BatchGetRolesRequest
 */
export type BatchGetRolesRequest = Message<"chatto.api.v1.BatchGetRolesRequest"> & {
  /**
   * Required role names. Unknown names are omitted from the response.
   *
   * @generated from field: repeated string names = 1;
   */
  names: string[];
};

/**
 * Describes the message chatto.api.v1.BatchGetRolesRequest.
 * Use `create(BatchGetRolesRequestSchema)` to create a new message.
 */
export const BatchGetRolesRequestSchema: GenMessage<BatchGetRolesRequest> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 5);

/**
 * Batch public role response.
 *
 * @generated from message chatto.api.v1.BatchGetRolesResponse
 */
export type BatchGetRolesResponse = Message<"chatto.api.v1.BatchGetRolesResponse"> & {
  /**
   * Found roles. The server preserves first-seen request order and
   * de-duplicates repeated names.
   *
   * @generated from field: repeated chatto.api.v1.Role roles = 1;
   */
  roles: Role[];
};

/**
 * Describes the message chatto.api.v1.BatchGetRolesResponse.
 * Use `create(BatchGetRolesResponseSchema)` to create a new message.
 */
export const BatchGetRolesResponseSchema: GenMessage<BatchGetRolesResponse> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_roles, 6);

/**
 * Provides authenticated reads for public role metadata.
 *
 * @generated from service chatto.api.v1.RoleService
 */
export const RoleService: GenService<{
  /**
   * Lists the current role catalog as a finite snapshot. Requires an
   * authenticated user.
   *
   * @generated from rpc chatto.api.v1.RoleService.ListRoles
   */
  listRoles: {
    methodKind: "unary";
    input: typeof ListRolesRequestSchema;
    output: typeof ListRolesResponseSchema;
  },
  /**
   * Gets one public role by stable name. Returns NOT_FOUND when the role is
   * unknown.
   *
   * @generated from rpc chatto.api.v1.RoleService.GetRole
   */
  getRole: {
    methodKind: "unary";
    input: typeof GetRoleRequestSchema;
    output: typeof GetRoleResponseSchema;
  },
  /**
   * Gets public role records for multiple role names referenced by member rows,
   * mentions, or integration clients.
   *
   * @generated from rpc chatto.api.v1.RoleService.BatchGetRoles
   */
  batchGetRoles: {
    methodKind: "unary";
    input: typeof BatchGetRolesRequestSchema;
    output: typeof BatchGetRolesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_chatto_api_v1_roles, 0);
