// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file chatto/api/v1/server.proto (package chatto.api.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { ProviderMetadata } from "./common_pb.js";
import { file_chatto_api_v1_common } from "./common_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file chatto/api/v1/server.proto.
 */
export const file_chatto_api_v1_server: GenFile = /*@__PURE__*/
  fileDesc("ChpjaGF0dG8vYXBpL3YxL3NlcnZlci5wcm90bxINY2hhdHRvLmFwaS52MSLyAQoTU2VydmVyUHVibGljUHJvZmlsZRIMCgRuYW1lGAEgASgJEg8KB3ZlcnNpb24YAiABKAkSFQoIbG9nb191cmwYAyABKAlIAIgBARIXCgpiYW5uZXJfdXJsGAQgASgJSAGIAQESHAoPd2VsY29tZV9tZXNzYWdlGAUgASgJSAKIAQESGAoLZGVzY3JpcHRpb24YBiABKAlIA4gBARIUCgxjYXBhYmlsaXRpZXMYByADKAlCCwoJX2xvZ29fdXJsQg0KC19iYW5uZXJfdXJsQhIKEF93ZWxjb21lX21lc3NhZ2VCDgoMX2Rlc2NyaXB0aW9uIn0KC1NlcnZlckxvZ2luEiMKG2RpcmVjdF9yZWdpc3RyYXRpb25fZW5hYmxlZBgBIAEoCBIyCglwcm92aWRlcnMYAiADKAsyHy5jaGF0dG8uYXBpLnYxLlByb3ZpZGVyTWV0YWRhdGESFQoNYXV0aG9yaXplX3VybBgDIAEoCUKnAQoRY29tLmNoYXR0by5hcGkudjFCC1NlcnZlclByb3RvUAFaL2htYW5zLmRlL2NoYXR0by9pbnRlcm5hbC9wYi9jaGF0dG8vYXBpL3YxO2FwaXYxogIDQ0FYqgINQ2hhdHRvLkFwaS5WMcoCDUNoYXR0b1xBcGlcVjHiAhlDaGF0dG9cQXBpXFYxXEdQQk1ldGFkYXRh6gIPQ2hhdHRvOjpBcGk6OlYxYgZwcm90bzM", [file_chatto_api_v1_common]);

/**
 * Public server profile, identity, and branding fields.
 *
 * @generated from message chatto.api.v1.ServerPublicProfile
 */
export type ServerPublicProfile = Message<"chatto.api.v1.ServerPublicProfile"> & {
  /**
   * Display name of the Towk server.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Server software version.
   *
   * @generated from field: string version = 2;
   */
  version: string;

  /**
   * Optional server logo URL.
   *
   * @generated from field: optional string logo_url = 3;
   */
  logoUrl?: string | undefined;

  /**
   * Optional server banner URL.
   *
   * @generated from field: optional string banner_url = 4;
   */
  bannerUrl?: string | undefined;

  /**
   * Optional welcome message.
   *
   * @generated from field: optional string welcome_message = 5;
   */
  welcomeMessage?: string | undefined;

  /**
   * Optional server description.
   *
   * @generated from field: optional string description = 6;
   */
  description?: string | undefined;

  /**
   * Stable, additive feature identifiers supported by this server. Clients
   * must ignore unknown values and require an explicit match before using a
   * capability whose fallback would not be safe.
   *
   * @generated from field: repeated string capabilities = 7;
   */
  capabilities: string[];
};

/**
 * Describes the message chatto.api.v1.ServerPublicProfile.
 * Use `create(ServerPublicProfileSchema)` to create a new message.
 */
export const ServerPublicProfileSchema: GenMessage<ServerPublicProfile> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_server, 0);

/**
 * Login and registration options exposed before authentication.
 *
 * @generated from message chatto.api.v1.ServerLogin
 */
export type ServerLogin = Message<"chatto.api.v1.ServerLogin"> & {
  /**
   * Whether users can create accounts through the public UI.
   *
   * @generated from field: bool direct_registration_enabled = 1;
   */
  directRegistrationEnabled: boolean;

  /**
   * Configured login providers.
   *
   * @generated from field: repeated chatto.api.v1.ProviderMetadata providers = 2;
   */
  providers: ProviderMetadata[];

  /**
   * URL for the legacy authorization flow, when enabled.
   *
   * @generated from field: string authorize_url = 3;
   */
  authorizeUrl: string;
};

/**
 * Describes the message chatto.api.v1.ServerLogin.
 * Use `create(ServerLoginSchema)` to create a new message.
 */
export const ServerLoginSchema: GenMessage<ServerLogin> = /*@__PURE__*/
  messageDesc(file_chatto_api_v1_server, 1);
