// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/admin/v1/diagnostics.proto

package adminv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Runtime performance profile exposed to server owners.
type AdminPerformanceProfile int32

const (
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED AdminPerformanceProfile = 0
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_ECONOMY     AdminPerformanceProfile = 1
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_BALANCED    AdminPerformanceProfile = 2
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_PERFORMANCE AdminPerformanceProfile = 3
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_CUSTOM      AdminPerformanceProfile = 4
	AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_LEGACY      AdminPerformanceProfile = 5
)

// Enum value maps for AdminPerformanceProfile.
var (
	AdminPerformanceProfile_name = map[int32]string{
		0: "ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED",
		1: "ADMIN_PERFORMANCE_PROFILE_ECONOMY",
		2: "ADMIN_PERFORMANCE_PROFILE_BALANCED",
		3: "ADMIN_PERFORMANCE_PROFILE_PERFORMANCE",
		4: "ADMIN_PERFORMANCE_PROFILE_CUSTOM",
		5: "ADMIN_PERFORMANCE_PROFILE_LEGACY",
	}
	AdminPerformanceProfile_value = map[string]int32{
		"ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED": 0,
		"ADMIN_PERFORMANCE_PROFILE_ECONOMY":     1,
		"ADMIN_PERFORMANCE_PROFILE_BALANCED":    2,
		"ADMIN_PERFORMANCE_PROFILE_PERFORMANCE": 3,
		"ADMIN_PERFORMANCE_PROFILE_CUSTOM":      4,
		"ADMIN_PERFORMANCE_PROFILE_LEGACY":      5,
	}
)

func (x AdminPerformanceProfile) Enum() *AdminPerformanceProfile {
	p := new(AdminPerformanceProfile)
	*p = x
	return p
}

func (x AdminPerformanceProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminPerformanceProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_diagnostics_proto_enumTypes[0].Descriptor()
}

func (AdminPerformanceProfile) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_diagnostics_proto_enumTypes[0]
}

func (x AdminPerformanceProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminPerformanceProfile.Descriptor instead.
func (AdminPerformanceProfile) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{0}
}

// Source of the currently requested runtime policy.
type AdminPerformancePolicySource int32

const (
	AdminPerformancePolicySource_ADMIN_PERFORMANCE_POLICY_SOURCE_UNSPECIFIED      AdminPerformancePolicySource = 0
	AdminPerformancePolicySource_ADMIN_PERFORMANCE_POLICY_SOURCE_HISTORICAL       AdminPerformancePolicySource = 1
	AdminPerformancePolicySource_ADMIN_PERFORMANCE_POLICY_SOURCE_OPERATOR_DEFAULT AdminPerformancePolicySource = 2
	AdminPerformancePolicySource_ADMIN_PERFORMANCE_POLICY_SOURCE_OWNER            AdminPerformancePolicySource = 3
)

// Enum value maps for AdminPerformancePolicySource.
var (
	AdminPerformancePolicySource_name = map[int32]string{
		0: "ADMIN_PERFORMANCE_POLICY_SOURCE_UNSPECIFIED",
		1: "ADMIN_PERFORMANCE_POLICY_SOURCE_HISTORICAL",
		2: "ADMIN_PERFORMANCE_POLICY_SOURCE_OPERATOR_DEFAULT",
		3: "ADMIN_PERFORMANCE_POLICY_SOURCE_OWNER",
	}
	AdminPerformancePolicySource_value = map[string]int32{
		"ADMIN_PERFORMANCE_POLICY_SOURCE_UNSPECIFIED":      0,
		"ADMIN_PERFORMANCE_POLICY_SOURCE_HISTORICAL":       1,
		"ADMIN_PERFORMANCE_POLICY_SOURCE_OPERATOR_DEFAULT": 2,
		"ADMIN_PERFORMANCE_POLICY_SOURCE_OWNER":            3,
	}
)

func (x AdminPerformancePolicySource) Enum() *AdminPerformancePolicySource {
	p := new(AdminPerformancePolicySource)
	*p = x
	return p
}

func (x AdminPerformancePolicySource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminPerformancePolicySource) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_diagnostics_proto_enumTypes[1].Descriptor()
}

func (AdminPerformancePolicySource) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_diagnostics_proto_enumTypes[1]
}

func (x AdminPerformancePolicySource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminPerformancePolicySource.Descriptor instead.
func (AdminPerformancePolicySource) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{1}
}

// Runtime work pools controlled by a performance policy.
type AdminPerformanceLimitField int32

const (
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_UNSPECIFIED                AdminPerformanceLimitField = 0
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_WORKERS    AdminPerformanceLimitField = 1
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_ADMISSIONS AdminPerformanceLimitField = 2
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_ASSET_UPLOAD_WORKERS       AdminPerformanceLimitField = 3
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_LINK_PREVIEW_WORKERS       AdminPerformanceLimitField = 4
	AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_VIDEO_WORKERS              AdminPerformanceLimitField = 5
)

// Enum value maps for AdminPerformanceLimitField.
var (
	AdminPerformanceLimitField_name = map[int32]string{
		0: "ADMIN_PERFORMANCE_LIMIT_FIELD_UNSPECIFIED",
		1: "ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_WORKERS",
		2: "ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_ADMISSIONS",
		3: "ADMIN_PERFORMANCE_LIMIT_FIELD_ASSET_UPLOAD_WORKERS",
		4: "ADMIN_PERFORMANCE_LIMIT_FIELD_LINK_PREVIEW_WORKERS",
		5: "ADMIN_PERFORMANCE_LIMIT_FIELD_VIDEO_WORKERS",
	}
	AdminPerformanceLimitField_value = map[string]int32{
		"ADMIN_PERFORMANCE_LIMIT_FIELD_UNSPECIFIED":                0,
		"ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_WORKERS":    1,
		"ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_ADMISSIONS": 2,
		"ADMIN_PERFORMANCE_LIMIT_FIELD_ASSET_UPLOAD_WORKERS":       3,
		"ADMIN_PERFORMANCE_LIMIT_FIELD_LINK_PREVIEW_WORKERS":       4,
		"ADMIN_PERFORMANCE_LIMIT_FIELD_VIDEO_WORKERS":              5,
	}
)

func (x AdminPerformanceLimitField) Enum() *AdminPerformanceLimitField {
	p := new(AdminPerformanceLimitField)
	*p = x
	return p
}

func (x AdminPerformanceLimitField) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminPerformanceLimitField) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_diagnostics_proto_enumTypes[2].Descriptor()
}

func (AdminPerformanceLimitField) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_diagnostics_proto_enumTypes[2]
}

func (x AdminPerformanceLimitField) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminPerformanceLimitField.Descriptor instead.
func (AdminPerformanceLimitField) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{2}
}

// Reason why an effective value is below its requested value.
type AdminPerformanceCapReason int32

const (
	AdminPerformanceCapReason_ADMIN_PERFORMANCE_CAP_REASON_UNSPECIFIED    AdminPerformanceCapReason = 0
	AdminPerformanceCapReason_ADMIN_PERFORMANCE_CAP_REASON_OPERATOR_CAP   AdminPerformanceCapReason = 1
	AdminPerformanceCapReason_ADMIN_PERFORMANCE_CAP_REASON_PROCESS_CPU    AdminPerformanceCapReason = 2
	AdminPerformanceCapReason_ADMIN_PERFORMANCE_CAP_REASON_PROCESS_MEMORY AdminPerformanceCapReason = 3
)

// Enum value maps for AdminPerformanceCapReason.
var (
	AdminPerformanceCapReason_name = map[int32]string{
		0: "ADMIN_PERFORMANCE_CAP_REASON_UNSPECIFIED",
		1: "ADMIN_PERFORMANCE_CAP_REASON_OPERATOR_CAP",
		2: "ADMIN_PERFORMANCE_CAP_REASON_PROCESS_CPU",
		3: "ADMIN_PERFORMANCE_CAP_REASON_PROCESS_MEMORY",
	}
	AdminPerformanceCapReason_value = map[string]int32{
		"ADMIN_PERFORMANCE_CAP_REASON_UNSPECIFIED":    0,
		"ADMIN_PERFORMANCE_CAP_REASON_OPERATOR_CAP":   1,
		"ADMIN_PERFORMANCE_CAP_REASON_PROCESS_CPU":    2,
		"ADMIN_PERFORMANCE_CAP_REASON_PROCESS_MEMORY": 3,
	}
)

func (x AdminPerformanceCapReason) Enum() *AdminPerformanceCapReason {
	p := new(AdminPerformanceCapReason)
	*p = x
	return p
}

func (x AdminPerformanceCapReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AdminPerformanceCapReason) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_admin_v1_diagnostics_proto_enumTypes[3].Descriptor()
}

func (AdminPerformanceCapReason) Type() protoreflect.EnumType {
	return &file_chatto_admin_v1_diagnostics_proto_enumTypes[3]
}

func (x AdminPerformanceCapReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AdminPerformanceCapReason.Descriptor instead.
func (AdminPerformanceCapReason) EnumDescriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{3}
}

// Request to read owner-only server diagnostics.
type GetSystemInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoRequest) Reset() {
	*x = GetSystemInfoRequest{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoRequest) ProtoMessage() {}

func (x *GetSystemInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoRequest.ProtoReflect.Descriptor instead.
func (*GetSystemInfoRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{0}
}

// Owner-only operational diagnostics for the Towk server.
type GetSystemInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Broker connection, account, and JetStream state.
	SystemInfo *AdminSystemInfo `protobuf:"bytes,1,opt,name=system_info,json=systemInfo,proto3" json:"system_info,omitempty"`
	// Event-sourced projection health and memory estimates.
	Projections   []*AdminProjectionState `protobuf:"bytes,2,rep,name=projections,proto3" json:"projections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemInfoResponse) Reset() {
	*x = GetSystemInfoResponse{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemInfoResponse) ProtoMessage() {}

func (x *GetSystemInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemInfoResponse.ProtoReflect.Descriptor instead.
func (*GetSystemInfoResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{1}
}

func (x *GetSystemInfoResponse) GetSystemInfo() *AdminSystemInfo {
	if x != nil {
		return x.SystemInfo
	}
	return nil
}

func (x *GetSystemInfoResponse) GetProjections() []*AdminProjectionState {
	if x != nil {
		return x.Projections
	}
	return nil
}

// Bounded worker values for one runtime performance policy.
type AdminPerformanceLimits struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ImageTransformWorkers    int32                  `protobuf:"varint,1,opt,name=image_transform_workers,json=imageTransformWorkers,proto3" json:"image_transform_workers,omitempty"`
	ImageTransformAdmissions int32                  `protobuf:"varint,2,opt,name=image_transform_admissions,json=imageTransformAdmissions,proto3" json:"image_transform_admissions,omitempty"`
	AssetUploadWorkers       int32                  `protobuf:"varint,3,opt,name=asset_upload_workers,json=assetUploadWorkers,proto3" json:"asset_upload_workers,omitempty"`
	LinkPreviewWorkers       int32                  `protobuf:"varint,4,opt,name=link_preview_workers,json=linkPreviewWorkers,proto3" json:"link_preview_workers,omitempty"`
	VideoWorkers             int32                  `protobuf:"varint,5,opt,name=video_workers,json=videoWorkers,proto3" json:"video_workers,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *AdminPerformanceLimits) Reset() {
	*x = AdminPerformanceLimits{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPerformanceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPerformanceLimits) ProtoMessage() {}

func (x *AdminPerformanceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPerformanceLimits.ProtoReflect.Descriptor instead.
func (*AdminPerformanceLimits) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{2}
}

func (x *AdminPerformanceLimits) GetImageTransformWorkers() int32 {
	if x != nil {
		return x.ImageTransformWorkers
	}
	return 0
}

func (x *AdminPerformanceLimits) GetImageTransformAdmissions() int32 {
	if x != nil {
		return x.ImageTransformAdmissions
	}
	return 0
}

func (x *AdminPerformanceLimits) GetAssetUploadWorkers() int32 {
	if x != nil {
		return x.AssetUploadWorkers
	}
	return 0
}

func (x *AdminPerformanceLimits) GetLinkPreviewWorkers() int32 {
	if x != nil {
		return x.LinkPreviewWorkers
	}
	return 0
}

func (x *AdminPerformanceLimits) GetVideoWorkers() int32 {
	if x != nil {
		return x.VideoWorkers
	}
	return 0
}

// Process-visible resource envelope used to compute effective values.
type AdminPerformanceEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cpus          int32                  `protobuf:"varint,1,opt,name=cpus,proto3" json:"cpus,omitempty"`
	MemoryBytes   int64                  `protobuf:"varint,2,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	CpuSource     string                 `protobuf:"bytes,3,opt,name=cpu_source,json=cpuSource,proto3" json:"cpu_source,omitempty"`
	MemorySource  string                 `protobuf:"bytes,4,opt,name=memory_source,json=memorySource,proto3" json:"memory_source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPerformanceEnvelope) Reset() {
	*x = AdminPerformanceEnvelope{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPerformanceEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPerformanceEnvelope) ProtoMessage() {}

func (x *AdminPerformanceEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPerformanceEnvelope.ProtoReflect.Descriptor instead.
func (*AdminPerformanceEnvelope) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{3}
}

func (x *AdminPerformanceEnvelope) GetCpus() int32 {
	if x != nil {
		return x.Cpus
	}
	return 0
}

func (x *AdminPerformanceEnvelope) GetMemoryBytes() int64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

func (x *AdminPerformanceEnvelope) GetCpuSource() string {
	if x != nil {
		return x.CpuSource
	}
	return ""
}

func (x *AdminPerformanceEnvelope) GetMemorySource() string {
	if x != nil {
		return x.MemorySource
	}
	return ""
}

// Reduction reasons for one runtime work pool.
type AdminPerformanceLimitCap struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Field         AdminPerformanceLimitField  `protobuf:"varint,1,opt,name=field,proto3,enum=chatto.admin.v1.AdminPerformanceLimitField" json:"field,omitempty"`
	Reasons       []AdminPerformanceCapReason `protobuf:"varint,2,rep,packed,name=reasons,proto3,enum=chatto.admin.v1.AdminPerformanceCapReason" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminPerformanceLimitCap) Reset() {
	*x = AdminPerformanceLimitCap{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPerformanceLimitCap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPerformanceLimitCap) ProtoMessage() {}

func (x *AdminPerformanceLimitCap) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPerformanceLimitCap.ProtoReflect.Descriptor instead.
func (*AdminPerformanceLimitCap) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{4}
}

func (x *AdminPerformanceLimitCap) GetField() AdminPerformanceLimitField {
	if x != nil {
		return x.Field
	}
	return AdminPerformanceLimitField_ADMIN_PERFORMANCE_LIMIT_FIELD_UNSPECIFIED
}

func (x *AdminPerformanceLimitCap) GetReasons() []AdminPerformanceCapReason {
	if x != nil {
		return x.Reasons
	}
	return nil
}

// Requested and effective performance state. Operator caps use zero to mean
// automatic process-envelope derivation, never unlimited.
type AdminPerformanceSettings struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	RequestedProfile AdminPerformanceProfile      `protobuf:"varint,1,opt,name=requested_profile,json=requestedProfile,proto3,enum=chatto.admin.v1.AdminPerformanceProfile" json:"requested_profile,omitempty"`
	EffectiveProfile AdminPerformanceProfile      `protobuf:"varint,2,opt,name=effective_profile,json=effectiveProfile,proto3,enum=chatto.admin.v1.AdminPerformanceProfile" json:"effective_profile,omitempty"`
	Source           AdminPerformancePolicySource `protobuf:"varint,3,opt,name=source,proto3,enum=chatto.admin.v1.AdminPerformancePolicySource" json:"source,omitempty"`
	SchemaVersion    uint32                       `protobuf:"varint,4,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	Revision         string                       `protobuf:"bytes,5,opt,name=revision,proto3" json:"revision,omitempty"`
	RequestedLimits  *AdminPerformanceLimits      `protobuf:"bytes,6,opt,name=requested_limits,json=requestedLimits,proto3" json:"requested_limits,omitempty"`
	EffectiveLimits  *AdminPerformanceLimits      `protobuf:"bytes,7,opt,name=effective_limits,json=effectiveLimits,proto3" json:"effective_limits,omitempty"`
	OperatorCaps     *AdminPerformanceLimits      `protobuf:"bytes,8,opt,name=operator_caps,json=operatorCaps,proto3" json:"operator_caps,omitempty"`
	Envelope         *AdminPerformanceEnvelope    `protobuf:"bytes,9,opt,name=envelope,proto3" json:"envelope,omitempty"`
	Caps             []*AdminPerformanceLimitCap  `protobuf:"bytes,10,rep,name=caps,proto3" json:"caps,omitempty"`
	PolicyError      string                       `protobuf:"bytes,11,opt,name=policy_error,json=policyError,proto3" json:"policy_error,omitempty"`
	RestartRequired  bool                         `protobuf:"varint,12,opt,name=restart_required,json=restartRequired,proto3" json:"restart_required,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdminPerformanceSettings) Reset() {
	*x = AdminPerformanceSettings{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminPerformanceSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminPerformanceSettings) ProtoMessage() {}

func (x *AdminPerformanceSettings) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminPerformanceSettings.ProtoReflect.Descriptor instead.
func (*AdminPerformanceSettings) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{5}
}

func (x *AdminPerformanceSettings) GetRequestedProfile() AdminPerformanceProfile {
	if x != nil {
		return x.RequestedProfile
	}
	return AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED
}

func (x *AdminPerformanceSettings) GetEffectiveProfile() AdminPerformanceProfile {
	if x != nil {
		return x.EffectiveProfile
	}
	return AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED
}

func (x *AdminPerformanceSettings) GetSource() AdminPerformancePolicySource {
	if x != nil {
		return x.Source
	}
	return AdminPerformancePolicySource_ADMIN_PERFORMANCE_POLICY_SOURCE_UNSPECIFIED
}

func (x *AdminPerformanceSettings) GetSchemaVersion() uint32 {
	if x != nil {
		return x.SchemaVersion
	}
	return 0
}

func (x *AdminPerformanceSettings) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *AdminPerformanceSettings) GetRequestedLimits() *AdminPerformanceLimits {
	if x != nil {
		return x.RequestedLimits
	}
	return nil
}

func (x *AdminPerformanceSettings) GetEffectiveLimits() *AdminPerformanceLimits {
	if x != nil {
		return x.EffectiveLimits
	}
	return nil
}

func (x *AdminPerformanceSettings) GetOperatorCaps() *AdminPerformanceLimits {
	if x != nil {
		return x.OperatorCaps
	}
	return nil
}

func (x *AdminPerformanceSettings) GetEnvelope() *AdminPerformanceEnvelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

func (x *AdminPerformanceSettings) GetCaps() []*AdminPerformanceLimitCap {
	if x != nil {
		return x.Caps
	}
	return nil
}

func (x *AdminPerformanceSettings) GetPolicyError() string {
	if x != nil {
		return x.PolicyError
	}
	return ""
}

func (x *AdminPerformanceSettings) GetRestartRequired() bool {
	if x != nil {
		return x.RestartRequired
	}
	return false
}

type GetPerformanceSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceSettingsRequest) Reset() {
	*x = GetPerformanceSettingsRequest{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceSettingsRequest) ProtoMessage() {}

func (x *GetPerformanceSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetPerformanceSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{6}
}

type GetPerformanceSettingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Settings      *AdminPerformanceSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPerformanceSettingsResponse) Reset() {
	*x = GetPerformanceSettingsResponse{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPerformanceSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPerformanceSettingsResponse) ProtoMessage() {}

func (x *GetPerformanceSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPerformanceSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetPerformanceSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{7}
}

func (x *GetPerformanceSettingsResponse) GetSettings() *AdminPerformanceSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type UpdatePerformanceSettingsRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Profile          AdminPerformanceProfile `protobuf:"varint,1,opt,name=profile,proto3,enum=chatto.admin.v1.AdminPerformanceProfile" json:"profile,omitempty"`
	CustomLimits     *AdminPerformanceLimits `protobuf:"bytes,2,opt,name=custom_limits,json=customLimits,proto3" json:"custom_limits,omitempty"`
	ExpectedRevision string                  `protobuf:"bytes,3,opt,name=expected_revision,json=expectedRevision,proto3" json:"expected_revision,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdatePerformanceSettingsRequest) Reset() {
	*x = UpdatePerformanceSettingsRequest{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePerformanceSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePerformanceSettingsRequest) ProtoMessage() {}

func (x *UpdatePerformanceSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePerformanceSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdatePerformanceSettingsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{8}
}

func (x *UpdatePerformanceSettingsRequest) GetProfile() AdminPerformanceProfile {
	if x != nil {
		return x.Profile
	}
	return AdminPerformanceProfile_ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED
}

func (x *UpdatePerformanceSettingsRequest) GetCustomLimits() *AdminPerformanceLimits {
	if x != nil {
		return x.CustomLimits
	}
	return nil
}

func (x *UpdatePerformanceSettingsRequest) GetExpectedRevision() string {
	if x != nil {
		return x.ExpectedRevision
	}
	return ""
}

type UpdatePerformanceSettingsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Settings      *AdminPerformanceSettings `protobuf:"bytes,1,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePerformanceSettingsResponse) Reset() {
	*x = UpdatePerformanceSettingsResponse{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePerformanceSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePerformanceSettingsResponse) ProtoMessage() {}

func (x *UpdatePerformanceSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePerformanceSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdatePerformanceSettingsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{9}
}

func (x *UpdatePerformanceSettingsResponse) GetSettings() *AdminPerformanceSettings {
	if x != nil {
		return x.Settings
	}
	return nil
}

// Broker and application diagnostics shown on the server admin system page.
type AdminSystemInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current NATS server connection metadata.
	Connection *AdminConnectionInfo `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// JetStream account limits and usage.
	Account *AdminAccountInfo `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// JetStream stream and consumer diagnostics.
	Nats *AdminNatsStats `protobuf:"bytes,3,opt,name=nats,proto3" json:"nats,omitempty"`
	// Aggregate Towk object counts.
	Stats         *AdminServerStats `protobuf:"bytes,4,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminSystemInfo) Reset() {
	*x = AdminSystemInfo{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminSystemInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminSystemInfo) ProtoMessage() {}

func (x *AdminSystemInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminSystemInfo.ProtoReflect.Descriptor instead.
func (*AdminSystemInfo) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{10}
}

func (x *AdminSystemInfo) GetConnection() *AdminConnectionInfo {
	if x != nil {
		return x.Connection
	}
	return nil
}

func (x *AdminSystemInfo) GetAccount() *AdminAccountInfo {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *AdminSystemInfo) GetNats() *AdminNatsStats {
	if x != nil {
		return x.Nats
	}
	return nil
}

func (x *AdminSystemInfo) GetStats() *AdminServerStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

// Current NATS server connection metadata.
type AdminConnectionInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether Towk is currently connected to NATS.
	Connected bool `protobuf:"varint,1,opt,name=connected,proto3" json:"connected,omitempty"`
	// Connected NATS server ID.
	ServerId string `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// Connected NATS server name.
	ServerName string `protobuf:"bytes,3,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// Connected NATS server version.
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	// Maximum payload accepted by the connected NATS server.
	MaxPayload int64 `protobuf:"varint,5,opt,name=max_payload,json=maxPayload,proto3" json:"max_payload,omitempty"`
	// Round-trip latency to the connected NATS server.
	Rtt           string `protobuf:"bytes,6,opt,name=rtt,proto3" json:"rtt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminConnectionInfo) Reset() {
	*x = AdminConnectionInfo{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminConnectionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminConnectionInfo) ProtoMessage() {}

func (x *AdminConnectionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminConnectionInfo.ProtoReflect.Descriptor instead.
func (*AdminConnectionInfo) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{11}
}

func (x *AdminConnectionInfo) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *AdminConnectionInfo) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AdminConnectionInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *AdminConnectionInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AdminConnectionInfo) GetMaxPayload() int64 {
	if x != nil {
		return x.MaxPayload
	}
	return 0
}

func (x *AdminConnectionInfo) GetRtt() string {
	if x != nil {
		return x.Rtt
	}
	return ""
}

// JetStream account limits and usage.
type AdminAccountInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum memory storage in bytes. Values less than or equal to zero mean unlimited.
	Memory int64 `protobuf:"varint,1,opt,name=memory,proto3" json:"memory,omitempty"`
	// Used memory storage in bytes.
	MemoryUsed int64 `protobuf:"varint,2,opt,name=memory_used,json=memoryUsed,proto3" json:"memory_used,omitempty"`
	// Maximum file storage in bytes. Values less than or equal to zero mean unlimited.
	Storage int64 `protobuf:"varint,3,opt,name=storage,proto3" json:"storage,omitempty"`
	// Used file storage in bytes.
	StorageUsed int64 `protobuf:"varint,4,opt,name=storage_used,json=storageUsed,proto3" json:"storage_used,omitempty"`
	// Maximum number of streams. Values less than or equal to zero mean unlimited.
	Streams int32 `protobuf:"varint,5,opt,name=streams,proto3" json:"streams,omitempty"`
	// Current number of streams.
	StreamsUsed int32 `protobuf:"varint,6,opt,name=streams_used,json=streamsUsed,proto3" json:"streams_used,omitempty"`
	// Maximum number of consumers. Values less than or equal to zero mean unlimited.
	Consumers int32 `protobuf:"varint,7,opt,name=consumers,proto3" json:"consumers,omitempty"`
	// Current number of consumers.
	ConsumersUsed int32 `protobuf:"varint,8,opt,name=consumers_used,json=consumersUsed,proto3" json:"consumers_used,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminAccountInfo) Reset() {
	*x = AdminAccountInfo{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminAccountInfo) ProtoMessage() {}

func (x *AdminAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminAccountInfo.ProtoReflect.Descriptor instead.
func (*AdminAccountInfo) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{12}
}

func (x *AdminAccountInfo) GetMemory() int64 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *AdminAccountInfo) GetMemoryUsed() int64 {
	if x != nil {
		return x.MemoryUsed
	}
	return 0
}

func (x *AdminAccountInfo) GetStorage() int64 {
	if x != nil {
		return x.Storage
	}
	return 0
}

func (x *AdminAccountInfo) GetStorageUsed() int64 {
	if x != nil {
		return x.StorageUsed
	}
	return 0
}

func (x *AdminAccountInfo) GetStreams() int32 {
	if x != nil {
		return x.Streams
	}
	return 0
}

func (x *AdminAccountInfo) GetStreamsUsed() int32 {
	if x != nil {
		return x.StreamsUsed
	}
	return 0
}

func (x *AdminAccountInfo) GetConsumers() int32 {
	if x != nil {
		return x.Consumers
	}
	return 0
}

func (x *AdminAccountInfo) GetConsumersUsed() int32 {
	if x != nil {
		return x.ConsumersUsed
	}
	return 0
}

// Aggregate Towk object counts.
type AdminServerStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Registered user count.
	UserCount int32 `protobuf:"varint,1,opt,name=user_count,json=userCount,proto3" json:"user_count,omitempty"`
	// Channel room count.
	ChannelRoomCount int32 `protobuf:"varint,2,opt,name=channel_room_count,json=channelRoomCount,proto3" json:"channel_room_count,omitempty"`
	// Direct-message room count.
	DmRoomCount   int32 `protobuf:"varint,3,opt,name=dm_room_count,json=dmRoomCount,proto3" json:"dm_room_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminServerStats) Reset() {
	*x = AdminServerStats{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminServerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminServerStats) ProtoMessage() {}

func (x *AdminServerStats) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminServerStats.ProtoReflect.Descriptor instead.
func (*AdminServerStats) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{13}
}

func (x *AdminServerStats) GetUserCount() int32 {
	if x != nil {
		return x.UserCount
	}
	return 0
}

func (x *AdminServerStats) GetChannelRoomCount() int32 {
	if x != nil {
		return x.ChannelRoomCount
	}
	return 0
}

func (x *AdminServerStats) GetDmRoomCount() int32 {
	if x != nil {
		return x.DmRoomCount
	}
	return 0
}

// JetStream stream and consumer diagnostics.
type AdminNatsStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total messages stored across all streams.
	TotalMessages int64 `protobuf:"varint,1,opt,name=total_messages,json=totalMessages,proto3" json:"total_messages,omitempty"`
	// Total bytes stored across all streams.
	TotalBytes int64 `protobuf:"varint,2,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	// Total pending messages across all consumers.
	TotalConsumerPending int64 `protobuf:"varint,3,opt,name=total_consumer_pending,json=totalConsumerPending,proto3" json:"total_consumer_pending,omitempty"`
	// Total messages currently waiting for acknowledgement.
	TotalAckPending int32 `protobuf:"varint,4,opt,name=total_ack_pending,json=totalAckPending,proto3" json:"total_ack_pending,omitempty"`
	// Streams sorted by name.
	Streams []*AdminNatsStreamInfo `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	// Consumers sorted by stream and name.
	Consumers     []*AdminNatsConsumerInfo `protobuf:"bytes,6,rep,name=consumers,proto3" json:"consumers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNatsStats) Reset() {
	*x = AdminNatsStats{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNatsStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNatsStats) ProtoMessage() {}

func (x *AdminNatsStats) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNatsStats.ProtoReflect.Descriptor instead.
func (*AdminNatsStats) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{14}
}

func (x *AdminNatsStats) GetTotalMessages() int64 {
	if x != nil {
		return x.TotalMessages
	}
	return 0
}

func (x *AdminNatsStats) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *AdminNatsStats) GetTotalConsumerPending() int64 {
	if x != nil {
		return x.TotalConsumerPending
	}
	return 0
}

func (x *AdminNatsStats) GetTotalAckPending() int32 {
	if x != nil {
		return x.TotalAckPending
	}
	return 0
}

func (x *AdminNatsStats) GetStreams() []*AdminNatsStreamInfo {
	if x != nil {
		return x.Streams
	}
	return nil
}

func (x *AdminNatsStats) GetConsumers() []*AdminNatsConsumerInfo {
	if x != nil {
		return x.Consumers
	}
	return nil
}

// JetStream stream state.
type AdminNatsStreamInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Stream description.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Subjects stored in the stream.
	Subjects []string `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Storage backend name.
	Storage string `protobuf:"bytes,4,opt,name=storage,proto3" json:"storage,omitempty"`
	// Number of messages in the stream.
	Messages int64 `protobuf:"varint,5,opt,name=messages,proto3" json:"messages,omitempty"`
	// Number of bytes in the stream.
	Bytes int64 `protobuf:"varint,6,opt,name=bytes,proto3" json:"bytes,omitempty"`
	// First stream sequence.
	FirstSequence string `protobuf:"bytes,7,opt,name=first_sequence,json=firstSequence,proto3" json:"first_sequence,omitempty"`
	// Last stream sequence.
	LastSequence string `protobuf:"bytes,8,opt,name=last_sequence,json=lastSequence,proto3" json:"last_sequence,omitempty"`
	// Number of stream consumers.
	ConsumerCount int32 `protobuf:"varint,9,opt,name=consumer_count,json=consumerCount,proto3" json:"consumer_count,omitempty"`
	// Configured stream replica count.
	Replicas int32 `protobuf:"varint,10,opt,name=replicas,proto3" json:"replicas,omitempty"`
	// Current cluster leader, when reported by NATS.
	ClusterLeader string `protobuf:"bytes,11,opt,name=cluster_leader,json=clusterLeader,proto3" json:"cluster_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminNatsStreamInfo) Reset() {
	*x = AdminNatsStreamInfo{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNatsStreamInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNatsStreamInfo) ProtoMessage() {}

func (x *AdminNatsStreamInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNatsStreamInfo.ProtoReflect.Descriptor instead.
func (*AdminNatsStreamInfo) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{15}
}

func (x *AdminNatsStreamInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminNatsStreamInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AdminNatsStreamInfo) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *AdminNatsStreamInfo) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *AdminNatsStreamInfo) GetMessages() int64 {
	if x != nil {
		return x.Messages
	}
	return 0
}

func (x *AdminNatsStreamInfo) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *AdminNatsStreamInfo) GetFirstSequence() string {
	if x != nil {
		return x.FirstSequence
	}
	return ""
}

func (x *AdminNatsStreamInfo) GetLastSequence() string {
	if x != nil {
		return x.LastSequence
	}
	return ""
}

func (x *AdminNatsStreamInfo) GetConsumerCount() int32 {
	if x != nil {
		return x.ConsumerCount
	}
	return 0
}

func (x *AdminNatsStreamInfo) GetReplicas() int32 {
	if x != nil {
		return x.Replicas
	}
	return 0
}

func (x *AdminNatsStreamInfo) GetClusterLeader() string {
	if x != nil {
		return x.ClusterLeader
	}
	return ""
}

// JetStream consumer state.
type AdminNatsConsumerInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream that owns the consumer.
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// Consumer name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Durable name, when the consumer is durable.
	Durable string `protobuf:"bytes,3,opt,name=durable,proto3" json:"durable,omitempty"`
	// Single filter subject, when configured.
	FilterSubject string `protobuf:"bytes,4,opt,name=filter_subject,json=filterSubject,proto3" json:"filter_subject,omitempty"`
	// Multiple filter subjects, when configured.
	FilterSubjects []string `protobuf:"bytes,5,rep,name=filter_subjects,json=filterSubjects,proto3" json:"filter_subjects,omitempty"`
	// NATS acknowledgement policy.
	AckPolicy string `protobuf:"bytes,6,opt,name=ack_policy,json=ackPolicy,proto3" json:"ack_policy,omitempty"`
	// Whether this is a pull consumer.
	PullBased bool `protobuf:"varint,7,opt,name=pull_based,json=pullBased,proto3" json:"pull_based,omitempty"`
	// Whether this push consumer has an active subscription.
	PushBound bool `protobuf:"varint,8,opt,name=push_bound,json=pushBound,proto3" json:"push_bound,omitempty"`
	// Pending messages for this consumer.
	Pending int64 `protobuf:"varint,9,opt,name=pending,proto3" json:"pending,omitempty"`
	// Messages waiting for acknowledgement.
	AckPending int32 `protobuf:"varint,10,opt,name=ack_pending,json=ackPending,proto3" json:"ack_pending,omitempty"`
	// Redelivered message count.
	Redelivered int32 `protobuf:"varint,11,opt,name=redelivered,proto3" json:"redelivered,omitempty"`
	// Pull requests waiting for messages.
	Waiting int32 `protobuf:"varint,12,opt,name=waiting,proto3" json:"waiting,omitempty"`
	// Delivered consumer sequence.
	DeliveredConsumerSequence string `protobuf:"bytes,13,opt,name=delivered_consumer_sequence,json=deliveredConsumerSequence,proto3" json:"delivered_consumer_sequence,omitempty"`
	// Delivered stream sequence.
	DeliveredStreamSequence string `protobuf:"bytes,14,opt,name=delivered_stream_sequence,json=deliveredStreamSequence,proto3" json:"delivered_stream_sequence,omitempty"`
	// Acknowledgement floor consumer sequence.
	AckFloorConsumerSequence string `protobuf:"bytes,15,opt,name=ack_floor_consumer_sequence,json=ackFloorConsumerSequence,proto3" json:"ack_floor_consumer_sequence,omitempty"`
	// Acknowledgement floor stream sequence.
	AckFloorStreamSequence string `protobuf:"bytes,16,opt,name=ack_floor_stream_sequence,json=ackFloorStreamSequence,proto3" json:"ack_floor_stream_sequence,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AdminNatsConsumerInfo) Reset() {
	*x = AdminNatsConsumerInfo{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminNatsConsumerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminNatsConsumerInfo) ProtoMessage() {}

func (x *AdminNatsConsumerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminNatsConsumerInfo.ProtoReflect.Descriptor instead.
func (*AdminNatsConsumerInfo) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{16}
}

func (x *AdminNatsConsumerInfo) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetDurable() string {
	if x != nil {
		return x.Durable
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetFilterSubject() string {
	if x != nil {
		return x.FilterSubject
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetFilterSubjects() []string {
	if x != nil {
		return x.FilterSubjects
	}
	return nil
}

func (x *AdminNatsConsumerInfo) GetAckPolicy() string {
	if x != nil {
		return x.AckPolicy
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetPullBased() bool {
	if x != nil {
		return x.PullBased
	}
	return false
}

func (x *AdminNatsConsumerInfo) GetPushBound() bool {
	if x != nil {
		return x.PushBound
	}
	return false
}

func (x *AdminNatsConsumerInfo) GetPending() int64 {
	if x != nil {
		return x.Pending
	}
	return 0
}

func (x *AdminNatsConsumerInfo) GetAckPending() int32 {
	if x != nil {
		return x.AckPending
	}
	return 0
}

func (x *AdminNatsConsumerInfo) GetRedelivered() int32 {
	if x != nil {
		return x.Redelivered
	}
	return 0
}

func (x *AdminNatsConsumerInfo) GetWaiting() int32 {
	if x != nil {
		return x.Waiting
	}
	return 0
}

func (x *AdminNatsConsumerInfo) GetDeliveredConsumerSequence() string {
	if x != nil {
		return x.DeliveredConsumerSequence
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetDeliveredStreamSequence() string {
	if x != nil {
		return x.DeliveredStreamSequence
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetAckFloorConsumerSequence() string {
	if x != nil {
		return x.AckFloorConsumerSequence
	}
	return ""
}

func (x *AdminNatsConsumerInfo) GetAckFloorStreamSequence() string {
	if x != nil {
		return x.AckFloorStreamSequence
	}
	return ""
}

// Event-sourced projection health and memory estimates.
type AdminProjectionState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable projection key.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Display name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// EVT subjects consumed by this projection.
	Subjects []string `protobuf:"bytes,3,rep,name=subjects,proto3" json:"subjects,omitempty"`
	// Whether the projection projector is running.
	Started bool `protobuf:"varint,4,opt,name=started,proto3" json:"started,omitempty"`
	// Startup duration in seconds, set after startup completes.
	StartupDurationSeconds *float64 `protobuf:"fixed64,5,opt,name=startup_duration_seconds,json=startupDurationSeconds,proto3,oneof" json:"startup_duration_seconds,omitempty"`
	// Last event sequence applied by the projection.
	LastAppliedSequence string `protobuf:"bytes,6,opt,name=last_applied_sequence,json=lastAppliedSequence,proto3" json:"last_applied_sequence,omitempty"`
	// Target sequence among the projection's matching subjects.
	MatchingStreamSequence string `protobuf:"bytes,7,opt,name=matching_stream_sequence,json=matchingStreamSequence,proto3" json:"matching_stream_sequence,omitempty"`
	// Current last sequence of the EVT stream.
	StreamLastSequence string `protobuf:"bytes,8,opt,name=stream_last_sequence,json=streamLastSequence,proto3" json:"stream_last_sequence,omitempty"`
	// Matching-subject lag between target and applied sequence.
	Lag int64 `protobuf:"varint,9,opt,name=lag,proto3" json:"lag,omitempty"`
	// Whether the projection failed.
	Failed bool `protobuf:"varint,10,opt,name=failed,proto3" json:"failed,omitempty"`
	// Sequence that failed, when failed is true.
	FailedSequence string `protobuf:"bytes,11,opt,name=failed_sequence,json=failedSequence,proto3" json:"failed_sequence,omitempty"`
	// Failure message, when failed is true.
	Failure string `protobuf:"bytes,12,opt,name=failure,proto3" json:"failure,omitempty"`
	// Estimated number of entries held by the projection.
	EntryCount int64 `protobuf:"varint,13,opt,name=entry_count,json=entryCount,proto3" json:"entry_count,omitempty"`
	// Estimated memory used by the projection in bytes.
	EstimatedBytes int64 `protobuf:"varint,14,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	// Estimated average memory per entry in bytes.
	AverageEntryBytes int64 `protobuf:"varint,15,opt,name=average_entry_bytes,json=averageEntryBytes,proto3" json:"average_entry_bytes,omitempty"`
	// Projection-specific diagnostic metrics.
	Metrics       []*AdminProjectionMetric `protobuf:"bytes,16,rep,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProjectionState) Reset() {
	*x = AdminProjectionState{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProjectionState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProjectionState) ProtoMessage() {}

func (x *AdminProjectionState) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProjectionState.ProtoReflect.Descriptor instead.
func (*AdminProjectionState) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{17}
}

func (x *AdminProjectionState) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AdminProjectionState) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProjectionState) GetSubjects() []string {
	if x != nil {
		return x.Subjects
	}
	return nil
}

func (x *AdminProjectionState) GetStarted() bool {
	if x != nil {
		return x.Started
	}
	return false
}

func (x *AdminProjectionState) GetStartupDurationSeconds() float64 {
	if x != nil && x.StartupDurationSeconds != nil {
		return *x.StartupDurationSeconds
	}
	return 0
}

func (x *AdminProjectionState) GetLastAppliedSequence() string {
	if x != nil {
		return x.LastAppliedSequence
	}
	return ""
}

func (x *AdminProjectionState) GetMatchingStreamSequence() string {
	if x != nil {
		return x.MatchingStreamSequence
	}
	return ""
}

func (x *AdminProjectionState) GetStreamLastSequence() string {
	if x != nil {
		return x.StreamLastSequence
	}
	return ""
}

func (x *AdminProjectionState) GetLag() int64 {
	if x != nil {
		return x.Lag
	}
	return 0
}

func (x *AdminProjectionState) GetFailed() bool {
	if x != nil {
		return x.Failed
	}
	return false
}

func (x *AdminProjectionState) GetFailedSequence() string {
	if x != nil {
		return x.FailedSequence
	}
	return ""
}

func (x *AdminProjectionState) GetFailure() string {
	if x != nil {
		return x.Failure
	}
	return ""
}

func (x *AdminProjectionState) GetEntryCount() int64 {
	if x != nil {
		return x.EntryCount
	}
	return 0
}

func (x *AdminProjectionState) GetEstimatedBytes() int64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

func (x *AdminProjectionState) GetAverageEntryBytes() int64 {
	if x != nil {
		return x.AverageEntryBytes
	}
	return 0
}

func (x *AdminProjectionState) GetMetrics() []*AdminProjectionMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Projection-specific diagnostic metric.
type AdminProjectionMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Metric name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Metric value.
	Value int64 `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	// Estimated memory represented by this metric in bytes.
	Bytes         int64 `protobuf:"varint,3,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminProjectionMetric) Reset() {
	*x = AdminProjectionMetric{}
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminProjectionMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminProjectionMetric) ProtoMessage() {}

func (x *AdminProjectionMetric) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_admin_v1_diagnostics_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminProjectionMetric.ProtoReflect.Descriptor instead.
func (*AdminProjectionMetric) Descriptor() ([]byte, []int) {
	return file_chatto_admin_v1_diagnostics_proto_rawDescGZIP(), []int{18}
}

func (x *AdminProjectionMetric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AdminProjectionMetric) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AdminProjectionMetric) GetBytes() int64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

var File_chatto_admin_v1_diagnostics_proto protoreflect.FileDescriptor

const file_chatto_admin_v1_diagnostics_proto_rawDesc = "" +
	"\n" +
	"!chatto/admin/v1/diagnostics.proto\x12\x0fchatto.admin.v1\x1a\x1bbuf/validate/validate.proto\"\x16\n" +
	"\x14GetSystemInfoRequest\"\xa3\x01\n" +
	"\x15GetSystemInfoResponse\x12A\n" +
	"\vsystem_info\x18\x01 \x01(\v2 .chatto.admin.v1.AdminSystemInfoR\n" +
	"systemInfo\x12G\n" +
	"\vprojections\x18\x02 \x03(\v2%.chatto.admin.v1.AdminProjectionStateR\vprojections\"\x97\x02\n" +
	"\x16AdminPerformanceLimits\x126\n" +
	"\x17image_transform_workers\x18\x01 \x01(\x05R\x15imageTransformWorkers\x12<\n" +
	"\x1aimage_transform_admissions\x18\x02 \x01(\x05R\x18imageTransformAdmissions\x120\n" +
	"\x14asset_upload_workers\x18\x03 \x01(\x05R\x12assetUploadWorkers\x120\n" +
	"\x14link_preview_workers\x18\x04 \x01(\x05R\x12linkPreviewWorkers\x12#\n" +
	"\rvideo_workers\x18\x05 \x01(\x05R\fvideoWorkers\"\x95\x01\n" +
	"\x18AdminPerformanceEnvelope\x12\x12\n" +
	"\x04cpus\x18\x01 \x01(\x05R\x04cpus\x12!\n" +
	"\fmemory_bytes\x18\x02 \x01(\x03R\vmemoryBytes\x12\x1d\n" +
	"\n" +
	"cpu_source\x18\x03 \x01(\tR\tcpuSource\x12#\n" +
	"\rmemory_source\x18\x04 \x01(\tR\fmemorySource\"\xa3\x01\n" +
	"\x18AdminPerformanceLimitCap\x12A\n" +
	"\x05field\x18\x01 \x01(\x0e2+.chatto.admin.v1.AdminPerformanceLimitFieldR\x05field\x12D\n" +
	"\areasons\x18\x02 \x03(\x0e2*.chatto.admin.v1.AdminPerformanceCapReasonR\areasons\"\x9c\x06\n" +
	"\x18AdminPerformanceSettings\x12U\n" +
	"\x11requested_profile\x18\x01 \x01(\x0e2(.chatto.admin.v1.AdminPerformanceProfileR\x10requestedProfile\x12U\n" +
	"\x11effective_profile\x18\x02 \x01(\x0e2(.chatto.admin.v1.AdminPerformanceProfileR\x10effectiveProfile\x12E\n" +
	"\x06source\x18\x03 \x01(\x0e2-.chatto.admin.v1.AdminPerformancePolicySourceR\x06source\x12%\n" +
	"\x0eschema_version\x18\x04 \x01(\rR\rschemaVersion\x12\x1a\n" +
	"\brevision\x18\x05 \x01(\tR\brevision\x12R\n" +
	"\x10requested_limits\x18\x06 \x01(\v2'.chatto.admin.v1.AdminPerformanceLimitsR\x0frequestedLimits\x12R\n" +
	"\x10effective_limits\x18\a \x01(\v2'.chatto.admin.v1.AdminPerformanceLimitsR\x0feffectiveLimits\x12L\n" +
	"\roperator_caps\x18\b \x01(\v2'.chatto.admin.v1.AdminPerformanceLimitsR\foperatorCaps\x12E\n" +
	"\benvelope\x18\t \x01(\v2).chatto.admin.v1.AdminPerformanceEnvelopeR\benvelope\x12=\n" +
	"\x04caps\x18\n" +
	" \x03(\v2).chatto.admin.v1.AdminPerformanceLimitCapR\x04caps\x12!\n" +
	"\fpolicy_error\x18\v \x01(\tR\vpolicyError\x12)\n" +
	"\x10restart_required\x18\f \x01(\bR\x0frestartRequired\"\x1f\n" +
	"\x1dGetPerformanceSettingsRequest\"g\n" +
	"\x1eGetPerformanceSettingsResponse\x12E\n" +
	"\bsettings\x18\x01 \x01(\v2).chatto.admin.v1.AdminPerformanceSettingsR\bsettings\"\xfa\x01\n" +
	" UpdatePerformanceSettingsRequest\x12P\n" +
	"\aprofile\x18\x01 \x01(\x0e2(.chatto.admin.v1.AdminPerformanceProfileB\f\xbaH\t\x82\x01\x06\x10\x01 \x00 \x05R\aprofile\x12L\n" +
	"\rcustom_limits\x18\x02 \x01(\v2'.chatto.admin.v1.AdminPerformanceLimitsR\fcustomLimits\x126\n" +
	"\x11expected_revision\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x14R\x10expectedRevision\"j\n" +
	"!UpdatePerformanceSettingsResponse\x12E\n" +
	"\bsettings\x18\x01 \x01(\v2).chatto.admin.v1.AdminPerformanceSettingsR\bsettings\"\x82\x02\n" +
	"\x0fAdminSystemInfo\x12D\n" +
	"\n" +
	"connection\x18\x01 \x01(\v2$.chatto.admin.v1.AdminConnectionInfoR\n" +
	"connection\x12;\n" +
	"\aaccount\x18\x02 \x01(\v2!.chatto.admin.v1.AdminAccountInfoR\aaccount\x123\n" +
	"\x04nats\x18\x03 \x01(\v2\x1f.chatto.admin.v1.AdminNatsStatsR\x04nats\x127\n" +
	"\x05stats\x18\x04 \x01(\v2!.chatto.admin.v1.AdminServerStatsR\x05stats\"\xbe\x01\n" +
	"\x13AdminConnectionInfo\x12\x1c\n" +
	"\tconnected\x18\x01 \x01(\bR\tconnected\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12\x1f\n" +
	"\vserver_name\x18\x03 \x01(\tR\n" +
	"serverName\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12\x1f\n" +
	"\vmax_payload\x18\x05 \x01(\x03R\n" +
	"maxPayload\x12\x10\n" +
	"\x03rtt\x18\x06 \x01(\tR\x03rtt\"\x8a\x02\n" +
	"\x10AdminAccountInfo\x12\x16\n" +
	"\x06memory\x18\x01 \x01(\x03R\x06memory\x12\x1f\n" +
	"\vmemory_used\x18\x02 \x01(\x03R\n" +
	"memoryUsed\x12\x18\n" +
	"\astorage\x18\x03 \x01(\x03R\astorage\x12!\n" +
	"\fstorage_used\x18\x04 \x01(\x03R\vstorageUsed\x12\x18\n" +
	"\astreams\x18\x05 \x01(\x05R\astreams\x12!\n" +
	"\fstreams_used\x18\x06 \x01(\x05R\vstreamsUsed\x12\x1c\n" +
	"\tconsumers\x18\a \x01(\x05R\tconsumers\x12%\n" +
	"\x0econsumers_used\x18\b \x01(\x05R\rconsumersUsed\"\x83\x01\n" +
	"\x10AdminServerStats\x12\x1d\n" +
	"\n" +
	"user_count\x18\x01 \x01(\x05R\tuserCount\x12,\n" +
	"\x12channel_room_count\x18\x02 \x01(\x05R\x10channelRoomCount\x12\"\n" +
	"\rdm_room_count\x18\x03 \x01(\x05R\vdmRoomCount\"\xc0\x02\n" +
	"\x0eAdminNatsStats\x12%\n" +
	"\x0etotal_messages\x18\x01 \x01(\x03R\rtotalMessages\x12\x1f\n" +
	"\vtotal_bytes\x18\x02 \x01(\x03R\n" +
	"totalBytes\x124\n" +
	"\x16total_consumer_pending\x18\x03 \x01(\x03R\x14totalConsumerPending\x12*\n" +
	"\x11total_ack_pending\x18\x04 \x01(\x05R\x0ftotalAckPending\x12>\n" +
	"\astreams\x18\x05 \x03(\v2$.chatto.admin.v1.AdminNatsStreamInfoR\astreams\x12D\n" +
	"\tconsumers\x18\x06 \x03(\v2&.chatto.admin.v1.AdminNatsConsumerInfoR\tconsumers\"\xe9\x02\n" +
	"\x13AdminNatsStreamInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bsubjects\x18\x03 \x03(\tR\bsubjects\x12\x18\n" +
	"\astorage\x18\x04 \x01(\tR\astorage\x12\x1a\n" +
	"\bmessages\x18\x05 \x01(\x03R\bmessages\x12\x14\n" +
	"\x05bytes\x18\x06 \x01(\x03R\x05bytes\x12%\n" +
	"\x0efirst_sequence\x18\a \x01(\tR\rfirstSequence\x12#\n" +
	"\rlast_sequence\x18\b \x01(\tR\flastSequence\x12%\n" +
	"\x0econsumer_count\x18\t \x01(\x05R\rconsumerCount\x12\x1a\n" +
	"\breplicas\x18\n" +
	" \x01(\x05R\breplicas\x12%\n" +
	"\x0ecluster_leader\x18\v \x01(\tR\rclusterLeader\"\xf7\x04\n" +
	"\x15AdminNatsConsumerInfo\x12\x16\n" +
	"\x06stream\x18\x01 \x01(\tR\x06stream\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\adurable\x18\x03 \x01(\tR\adurable\x12%\n" +
	"\x0efilter_subject\x18\x04 \x01(\tR\rfilterSubject\x12'\n" +
	"\x0ffilter_subjects\x18\x05 \x03(\tR\x0efilterSubjects\x12\x1d\n" +
	"\n" +
	"ack_policy\x18\x06 \x01(\tR\tackPolicy\x12\x1d\n" +
	"\n" +
	"pull_based\x18\a \x01(\bR\tpullBased\x12\x1d\n" +
	"\n" +
	"push_bound\x18\b \x01(\bR\tpushBound\x12\x18\n" +
	"\apending\x18\t \x01(\x03R\apending\x12\x1f\n" +
	"\vack_pending\x18\n" +
	" \x01(\x05R\n" +
	"ackPending\x12 \n" +
	"\vredelivered\x18\v \x01(\x05R\vredelivered\x12\x18\n" +
	"\awaiting\x18\f \x01(\x05R\awaiting\x12>\n" +
	"\x1bdelivered_consumer_sequence\x18\r \x01(\tR\x19deliveredConsumerSequence\x12:\n" +
	"\x19delivered_stream_sequence\x18\x0e \x01(\tR\x17deliveredStreamSequence\x12=\n" +
	"\x1back_floor_consumer_sequence\x18\x0f \x01(\tR\x18ackFloorConsumerSequence\x129\n" +
	"\x19ack_floor_stream_sequence\x18\x10 \x01(\tR\x16ackFloorStreamSequence\"\x97\x05\n" +
	"\x14AdminProjectionState\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubjects\x18\x03 \x03(\tR\bsubjects\x12\x18\n" +
	"\astarted\x18\x04 \x01(\bR\astarted\x12=\n" +
	"\x18startup_duration_seconds\x18\x05 \x01(\x01H\x00R\x16startupDurationSeconds\x88\x01\x01\x122\n" +
	"\x15last_applied_sequence\x18\x06 \x01(\tR\x13lastAppliedSequence\x128\n" +
	"\x18matching_stream_sequence\x18\a \x01(\tR\x16matchingStreamSequence\x120\n" +
	"\x14stream_last_sequence\x18\b \x01(\tR\x12streamLastSequence\x12\x10\n" +
	"\x03lag\x18\t \x01(\x03R\x03lag\x12\x16\n" +
	"\x06failed\x18\n" +
	" \x01(\bR\x06failed\x12'\n" +
	"\x0ffailed_sequence\x18\v \x01(\tR\x0efailedSequence\x12\x18\n" +
	"\afailure\x18\f \x01(\tR\afailure\x12\x1f\n" +
	"\ventry_count\x18\r \x01(\x03R\n" +
	"entryCount\x12'\n" +
	"\x0festimated_bytes\x18\x0e \x01(\x03R\x0eestimatedBytes\x12.\n" +
	"\x13average_entry_bytes\x18\x0f \x01(\x03R\x11averageEntryBytes\x12@\n" +
	"\ametrics\x18\x10 \x03(\v2&.chatto.admin.v1.AdminProjectionMetricR\ametricsB\x1b\n" +
	"\x19_startup_duration_seconds\"W\n" +
	"\x15AdminProjectionMetric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value\x12\x14\n" +
	"\x05bytes\x18\x03 \x01(\x03R\x05bytes*\x8a\x02\n" +
	"\x17AdminPerformanceProfile\x12)\n" +
	"%ADMIN_PERFORMANCE_PROFILE_UNSPECIFIED\x10\x00\x12%\n" +
	"!ADMIN_PERFORMANCE_PROFILE_ECONOMY\x10\x01\x12&\n" +
	"\"ADMIN_PERFORMANCE_PROFILE_BALANCED\x10\x02\x12)\n" +
	"%ADMIN_PERFORMANCE_PROFILE_PERFORMANCE\x10\x03\x12$\n" +
	" ADMIN_PERFORMANCE_PROFILE_CUSTOM\x10\x04\x12$\n" +
	" ADMIN_PERFORMANCE_PROFILE_LEGACY\x10\x05*\xe0\x01\n" +
	"\x1cAdminPerformancePolicySource\x12/\n" +
	"+ADMIN_PERFORMANCE_POLICY_SOURCE_UNSPECIFIED\x10\x00\x12.\n" +
	"*ADMIN_PERFORMANCE_POLICY_SOURCE_HISTORICAL\x10\x01\x124\n" +
	"0ADMIN_PERFORMANCE_POLICY_SOURCE_OPERATOR_DEFAULT\x10\x02\x12)\n" +
	"%ADMIN_PERFORMANCE_POLICY_SOURCE_OWNER\x10\x03*\xe5\x02\n" +
	"\x1aAdminPerformanceLimitField\x12-\n" +
	")ADMIN_PERFORMANCE_LIMIT_FIELD_UNSPECIFIED\x10\x00\x129\n" +
	"5ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_WORKERS\x10\x01\x12<\n" +
	"8ADMIN_PERFORMANCE_LIMIT_FIELD_IMAGE_TRANSFORM_ADMISSIONS\x10\x02\x126\n" +
	"2ADMIN_PERFORMANCE_LIMIT_FIELD_ASSET_UPLOAD_WORKERS\x10\x03\x126\n" +
	"2ADMIN_PERFORMANCE_LIMIT_FIELD_LINK_PREVIEW_WORKERS\x10\x04\x12/\n" +
	"+ADMIN_PERFORMANCE_LIMIT_FIELD_VIDEO_WORKERS\x10\x05*\xd7\x01\n" +
	"\x19AdminPerformanceCapReason\x12,\n" +
	"(ADMIN_PERFORMANCE_CAP_REASON_UNSPECIFIED\x10\x00\x12-\n" +
	")ADMIN_PERFORMANCE_CAP_REASON_OPERATOR_CAP\x10\x01\x12,\n" +
	"(ADMIN_PERFORMANCE_CAP_REASON_PROCESS_CPU\x10\x02\x12/\n" +
	"+ADMIN_PERFORMANCE_CAP_REASON_PROCESS_MEMORY\x10\x032\xf9\x02\n" +
	"\x17AdminDiagnosticsService\x12^\n" +
	"\rGetSystemInfo\x12%.chatto.admin.v1.GetSystemInfoRequest\x1a&.chatto.admin.v1.GetSystemInfoResponse\x12y\n" +
	"\x16GetPerformanceSettings\x12..chatto.admin.v1.GetPerformanceSettingsRequest\x1a/.chatto.admin.v1.GetPerformanceSettingsResponse\x12\x82\x01\n" +
	"\x19UpdatePerformanceSettings\x121.chatto.admin.v1.UpdatePerformanceSettingsRequest\x1a2.chatto.admin.v1.UpdatePerformanceSettingsResponseB\xba\x01\n" +
	"\x13com.chatto.admin.v1B\x10DiagnosticsProtoP\x01Z3hmans.de/chatto/internal/pb/chatto/admin/v1;adminv1\xa2\x02\x03CAX\xaa\x02\x0fChatto.Admin.V1\xca\x02\x0fChatto\\Admin\\V1\xe2\x02\x1bChatto\\Admin\\V1\\GPBMetadata\xea\x02\x11Chatto::Admin::V1b\x06proto3"

var (
	file_chatto_admin_v1_diagnostics_proto_rawDescOnce sync.Once
	file_chatto_admin_v1_diagnostics_proto_rawDescData []byte
)

func file_chatto_admin_v1_diagnostics_proto_rawDescGZIP() []byte {
	file_chatto_admin_v1_diagnostics_proto_rawDescOnce.Do(func() {
		file_chatto_admin_v1_diagnostics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_diagnostics_proto_rawDesc), len(file_chatto_admin_v1_diagnostics_proto_rawDesc)))
	})
	return file_chatto_admin_v1_diagnostics_proto_rawDescData
}

var file_chatto_admin_v1_diagnostics_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chatto_admin_v1_diagnostics_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_chatto_admin_v1_diagnostics_proto_goTypes = []any{
	(AdminPerformanceProfile)(0),              // 0: chatto.admin.v1.AdminPerformanceProfile
	(AdminPerformancePolicySource)(0),         // 1: chatto.admin.v1.AdminPerformancePolicySource
	(AdminPerformanceLimitField)(0),           // 2: chatto.admin.v1.AdminPerformanceLimitField
	(AdminPerformanceCapReason)(0),            // 3: chatto.admin.v1.AdminPerformanceCapReason
	(*GetSystemInfoRequest)(nil),              // 4: chatto.admin.v1.GetSystemInfoRequest
	(*GetSystemInfoResponse)(nil),             // 5: chatto.admin.v1.GetSystemInfoResponse
	(*AdminPerformanceLimits)(nil),            // 6: chatto.admin.v1.AdminPerformanceLimits
	(*AdminPerformanceEnvelope)(nil),          // 7: chatto.admin.v1.AdminPerformanceEnvelope
	(*AdminPerformanceLimitCap)(nil),          // 8: chatto.admin.v1.AdminPerformanceLimitCap
	(*AdminPerformanceSettings)(nil),          // 9: chatto.admin.v1.AdminPerformanceSettings
	(*GetPerformanceSettingsRequest)(nil),     // 10: chatto.admin.v1.GetPerformanceSettingsRequest
	(*GetPerformanceSettingsResponse)(nil),    // 11: chatto.admin.v1.GetPerformanceSettingsResponse
	(*UpdatePerformanceSettingsRequest)(nil),  // 12: chatto.admin.v1.UpdatePerformanceSettingsRequest
	(*UpdatePerformanceSettingsResponse)(nil), // 13: chatto.admin.v1.UpdatePerformanceSettingsResponse
	(*AdminSystemInfo)(nil),                   // 14: chatto.admin.v1.AdminSystemInfo
	(*AdminConnectionInfo)(nil),               // 15: chatto.admin.v1.AdminConnectionInfo
	(*AdminAccountInfo)(nil),                  // 16: chatto.admin.v1.AdminAccountInfo
	(*AdminServerStats)(nil),                  // 17: chatto.admin.v1.AdminServerStats
	(*AdminNatsStats)(nil),                    // 18: chatto.admin.v1.AdminNatsStats
	(*AdminNatsStreamInfo)(nil),               // 19: chatto.admin.v1.AdminNatsStreamInfo
	(*AdminNatsConsumerInfo)(nil),             // 20: chatto.admin.v1.AdminNatsConsumerInfo
	(*AdminProjectionState)(nil),              // 21: chatto.admin.v1.AdminProjectionState
	(*AdminProjectionMetric)(nil),             // 22: chatto.admin.v1.AdminProjectionMetric
}
var file_chatto_admin_v1_diagnostics_proto_depIdxs = []int32{
	14, // 0: chatto.admin.v1.GetSystemInfoResponse.system_info:type_name -> chatto.admin.v1.AdminSystemInfo
	21, // 1: chatto.admin.v1.GetSystemInfoResponse.projections:type_name -> chatto.admin.v1.AdminProjectionState
	2,  // 2: chatto.admin.v1.AdminPerformanceLimitCap.field:type_name -> chatto.admin.v1.AdminPerformanceLimitField
	3,  // 3: chatto.admin.v1.AdminPerformanceLimitCap.reasons:type_name -> chatto.admin.v1.AdminPerformanceCapReason
	0,  // 4: chatto.admin.v1.AdminPerformanceSettings.requested_profile:type_name -> chatto.admin.v1.AdminPerformanceProfile
	0,  // 5: chatto.admin.v1.AdminPerformanceSettings.effective_profile:type_name -> chatto.admin.v1.AdminPerformanceProfile
	1,  // 6: chatto.admin.v1.AdminPerformanceSettings.source:type_name -> chatto.admin.v1.AdminPerformancePolicySource
	6,  // 7: chatto.admin.v1.AdminPerformanceSettings.requested_limits:type_name -> chatto.admin.v1.AdminPerformanceLimits
	6,  // 8: chatto.admin.v1.AdminPerformanceSettings.effective_limits:type_name -> chatto.admin.v1.AdminPerformanceLimits
	6,  // 9: chatto.admin.v1.AdminPerformanceSettings.operator_caps:type_name -> chatto.admin.v1.AdminPerformanceLimits
	7,  // 10: chatto.admin.v1.AdminPerformanceSettings.envelope:type_name -> chatto.admin.v1.AdminPerformanceEnvelope
	8,  // 11: chatto.admin.v1.AdminPerformanceSettings.caps:type_name -> chatto.admin.v1.AdminPerformanceLimitCap
	9,  // 12: chatto.admin.v1.GetPerformanceSettingsResponse.settings:type_name -> chatto.admin.v1.AdminPerformanceSettings
	0,  // 13: chatto.admin.v1.UpdatePerformanceSettingsRequest.profile:type_name -> chatto.admin.v1.AdminPerformanceProfile
	6,  // 14: chatto.admin.v1.UpdatePerformanceSettingsRequest.custom_limits:type_name -> chatto.admin.v1.AdminPerformanceLimits
	9,  // 15: chatto.admin.v1.UpdatePerformanceSettingsResponse.settings:type_name -> chatto.admin.v1.AdminPerformanceSettings
	15, // 16: chatto.admin.v1.AdminSystemInfo.connection:type_name -> chatto.admin.v1.AdminConnectionInfo
	16, // 17: chatto.admin.v1.AdminSystemInfo.account:type_name -> chatto.admin.v1.AdminAccountInfo
	18, // 18: chatto.admin.v1.AdminSystemInfo.nats:type_name -> chatto.admin.v1.AdminNatsStats
	17, // 19: chatto.admin.v1.AdminSystemInfo.stats:type_name -> chatto.admin.v1.AdminServerStats
	19, // 20: chatto.admin.v1.AdminNatsStats.streams:type_name -> chatto.admin.v1.AdminNatsStreamInfo
	20, // 21: chatto.admin.v1.AdminNatsStats.consumers:type_name -> chatto.admin.v1.AdminNatsConsumerInfo
	22, // 22: chatto.admin.v1.AdminProjectionState.metrics:type_name -> chatto.admin.v1.AdminProjectionMetric
	4,  // 23: chatto.admin.v1.AdminDiagnosticsService.GetSystemInfo:input_type -> chatto.admin.v1.GetSystemInfoRequest
	10, // 24: chatto.admin.v1.AdminDiagnosticsService.GetPerformanceSettings:input_type -> chatto.admin.v1.GetPerformanceSettingsRequest
	12, // 25: chatto.admin.v1.AdminDiagnosticsService.UpdatePerformanceSettings:input_type -> chatto.admin.v1.UpdatePerformanceSettingsRequest
	5,  // 26: chatto.admin.v1.AdminDiagnosticsService.GetSystemInfo:output_type -> chatto.admin.v1.GetSystemInfoResponse
	11, // 27: chatto.admin.v1.AdminDiagnosticsService.GetPerformanceSettings:output_type -> chatto.admin.v1.GetPerformanceSettingsResponse
	13, // 28: chatto.admin.v1.AdminDiagnosticsService.UpdatePerformanceSettings:output_type -> chatto.admin.v1.UpdatePerformanceSettingsResponse
	26, // [26:29] is the sub-list for method output_type
	23, // [23:26] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_chatto_admin_v1_diagnostics_proto_init() }
func file_chatto_admin_v1_diagnostics_proto_init() {
	if File_chatto_admin_v1_diagnostics_proto != nil {
		return
	}
	file_chatto_admin_v1_diagnostics_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_admin_v1_diagnostics_proto_rawDesc), len(file_chatto_admin_v1_diagnostics_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_admin_v1_diagnostics_proto_goTypes,
		DependencyIndexes: file_chatto_admin_v1_diagnostics_proto_depIdxs,
		EnumInfos:         file_chatto_admin_v1_diagnostics_proto_enumTypes,
		MessageInfos:      file_chatto_admin_v1_diagnostics_proto_msgTypes,
	}.Build()
	File_chatto_admin_v1_diagnostics_proto = out.File
	file_chatto_admin_v1_diagnostics_proto_goTypes = nil
	file_chatto_admin_v1_diagnostics_proto_depIdxs = nil
}
