// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: chatto/core/v1/read_receipts.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublicReadReceiptCursor stores bounded public receipt coverage for one user
// and one room or thread timeline. It is separate from private unread markers.
type PublicReadReceiptCursor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disjoint monotonic intervals. A new interval begins after each policy
	// re-enable so reads performed while receipts were disabled are never
	// backfilled by a later cursor advance.
	Intervals     []*PublicReadReceiptInterval `protobuf:"bytes,1,rep,name=intervals,proto3" json:"intervals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicReadReceiptCursor) Reset() {
	*x = PublicReadReceiptCursor{}
	mi := &file_chatto_core_v1_read_receipts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicReadReceiptCursor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicReadReceiptCursor) ProtoMessage() {}

func (x *PublicReadReceiptCursor) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_read_receipts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicReadReceiptCursor.ProtoReflect.Descriptor instead.
func (*PublicReadReceiptCursor) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_read_receipts_proto_rawDescGZIP(), []int{0}
}

func (x *PublicReadReceiptCursor) GetIntervals() []*PublicReadReceiptInterval {
	if x != nil {
		return x.Intervals
	}
	return nil
}

// PublicReadReceiptInterval is one uninterrupted opt-in generation.
type PublicReadReceiptInterval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-recorded time at which the effective receipt policy became enabled.
	// Absent represents the original default-enabled generation.
	GenerationStartedAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=generation_started_at,json=generationStartedAt,proto3" json:"generation_started_at,omitempty"`
	// First room-stream sequence covered by this generation.
	StartEventSequence uint64 `protobuf:"varint,2,opt,name=start_event_sequence,json=startEventSequence,proto3" json:"start_event_sequence,omitempty"`
	// Highest message event covered by this generation.
	EndEventId string `protobuf:"bytes,3,opt,name=end_event_id,json=endEventId,proto3" json:"end_event_id,omitempty"`
	// Room-stream sequence for end_event_id.
	EndEventSequence uint64 `protobuf:"varint,4,opt,name=end_event_sequence,json=endEventSequence,proto3" json:"end_event_sequence,omitempty"`
	// Server time when this interval most recently advanced.
	ReadAt        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=read_at,json=readAt,proto3" json:"read_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicReadReceiptInterval) Reset() {
	*x = PublicReadReceiptInterval{}
	mi := &file_chatto_core_v1_read_receipts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicReadReceiptInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicReadReceiptInterval) ProtoMessage() {}

func (x *PublicReadReceiptInterval) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_core_v1_read_receipts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicReadReceiptInterval.ProtoReflect.Descriptor instead.
func (*PublicReadReceiptInterval) Descriptor() ([]byte, []int) {
	return file_chatto_core_v1_read_receipts_proto_rawDescGZIP(), []int{1}
}

func (x *PublicReadReceiptInterval) GetGenerationStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.GenerationStartedAt
	}
	return nil
}

func (x *PublicReadReceiptInterval) GetStartEventSequence() uint64 {
	if x != nil {
		return x.StartEventSequence
	}
	return 0
}

func (x *PublicReadReceiptInterval) GetEndEventId() string {
	if x != nil {
		return x.EndEventId
	}
	return ""
}

func (x *PublicReadReceiptInterval) GetEndEventSequence() uint64 {
	if x != nil {
		return x.EndEventSequence
	}
	return 0
}

func (x *PublicReadReceiptInterval) GetReadAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReadAt
	}
	return nil
}

var File_chatto_core_v1_read_receipts_proto protoreflect.FileDescriptor

const file_chatto_core_v1_read_receipts_proto_rawDesc = "" +
	"\n" +
	"\"chatto/core/v1/read_receipts.proto\x12\x0echatto.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"b\n" +
	"\x17PublicReadReceiptCursor\x12G\n" +
	"\tintervals\x18\x01 \x03(\v2).chatto.core.v1.PublicReadReceiptIntervalR\tintervals\"\xa2\x02\n" +
	"\x19PublicReadReceiptInterval\x12N\n" +
	"\x15generation_started_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x13generationStartedAt\x120\n" +
	"\x14start_event_sequence\x18\x02 \x01(\x04R\x12startEventSequence\x12 \n" +
	"\fend_event_id\x18\x03 \x01(\tR\n" +
	"endEventId\x12,\n" +
	"\x12end_event_sequence\x18\x04 \x01(\x04R\x10endEventSequence\x123\n" +
	"\aread_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x06readAtB\xb4\x01\n" +
	"\x12com.chatto.core.v1B\x11ReadReceiptsProtoP\x01Z1hmans.de/chatto/internal/pb/chatto/core/v1;corev1\xa2\x02\x03CCX\xaa\x02\x0eChatto.Core.V1\xca\x02\x0eChatto\\Core\\V1\xe2\x02\x1aChatto\\Core\\V1\\GPBMetadata\xea\x02\x10Chatto::Core::V1b\x06proto3"

var (
	file_chatto_core_v1_read_receipts_proto_rawDescOnce sync.Once
	file_chatto_core_v1_read_receipts_proto_rawDescData []byte
)

func file_chatto_core_v1_read_receipts_proto_rawDescGZIP() []byte {
	file_chatto_core_v1_read_receipts_proto_rawDescOnce.Do(func() {
		file_chatto_core_v1_read_receipts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_core_v1_read_receipts_proto_rawDesc), len(file_chatto_core_v1_read_receipts_proto_rawDesc)))
	})
	return file_chatto_core_v1_read_receipts_proto_rawDescData
}

var file_chatto_core_v1_read_receipts_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chatto_core_v1_read_receipts_proto_goTypes = []any{
	(*PublicReadReceiptCursor)(nil),   // 0: chatto.core.v1.PublicReadReceiptCursor
	(*PublicReadReceiptInterval)(nil), // 1: chatto.core.v1.PublicReadReceiptInterval
	(*timestamppb.Timestamp)(nil),     // 2: google.protobuf.Timestamp
}
var file_chatto_core_v1_read_receipts_proto_depIdxs = []int32{
	1, // 0: chatto.core.v1.PublicReadReceiptCursor.intervals:type_name -> chatto.core.v1.PublicReadReceiptInterval
	2, // 1: chatto.core.v1.PublicReadReceiptInterval.generation_started_at:type_name -> google.protobuf.Timestamp
	2, // 2: chatto.core.v1.PublicReadReceiptInterval.read_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_chatto_core_v1_read_receipts_proto_init() }
func file_chatto_core_v1_read_receipts_proto_init() {
	if File_chatto_core_v1_read_receipts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_core_v1_read_receipts_proto_rawDesc), len(file_chatto_core_v1_read_receipts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_chatto_core_v1_read_receipts_proto_goTypes,
		DependencyIndexes: file_chatto_core_v1_read_receipts_proto_depIdxs,
		MessageInfos:      file_chatto_core_v1_read_receipts_proto_msgTypes,
	}.Build()
	File_chatto_core_v1_read_receipts_proto = out.File
	file_chatto_core_v1_read_receipts_proto_goTypes = nil
	file_chatto_core_v1_read_receipts_proto_depIdxs = nil
}
