// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: chatto/api/v1/native_notifications.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "hmans.de/chatto/internal/pb/chatto/api/v1"
	http "net/http"
	strings "strings"
)

const _ = connect.IsAtLeastVersion1_13_0

const (
	NativeNotificationServiceName = "chatto.api.v1.NativeNotificationService"
)

const (
	NativeNotificationServiceGetNativeNotificationConfigProcedure = "/chatto.api.v1.NativeNotificationService/GetNativeNotificationConfig"
	NativeNotificationServiceRegisterNativeEndpointProcedure = "/chatto.api.v1.NativeNotificationService/RegisterNativeEndpoint"
	NativeNotificationServiceRotateNativeEndpointProcedure = "/chatto.api.v1.NativeNotificationService/RotateNativeEndpoint"
	NativeNotificationServiceUnregisterNativeEndpointProcedure = "/chatto.api.v1.NativeNotificationService/UnregisterNativeEndpoint"
	NativeNotificationServiceListNativeEndpointsProcedure = "/chatto.api.v1.NativeNotificationService/ListNativeEndpoints"
	NativeNotificationServiceUpdateNativeEndpointPreferencesProcedure = "/chatto.api.v1.NativeNotificationService/UpdateNativeEndpointPreferences"
)

type NativeNotificationServiceClient interface {
	GetNativeNotificationConfig(context.Context, *connect.Request[v1.GetNativeNotificationConfigRequest]) (*connect.Response[v1.GetNativeNotificationConfigResponse], error)
	RegisterNativeEndpoint(context.Context, *connect.Request[v1.RegisterNativeEndpointRequest]) (*connect.Response[v1.RegisterNativeEndpointResponse], error)
	RotateNativeEndpoint(context.Context, *connect.Request[v1.RotateNativeEndpointRequest]) (*connect.Response[v1.RotateNativeEndpointResponse], error)
	UnregisterNativeEndpoint(context.Context, *connect.Request[v1.UnregisterNativeEndpointRequest]) (*connect.Response[v1.UnregisterNativeEndpointResponse], error)
	ListNativeEndpoints(context.Context, *connect.Request[v1.ListNativeEndpointsRequest]) (*connect.Response[v1.ListNativeEndpointsResponse], error)
	UpdateNativeEndpointPreferences(context.Context, *connect.Request[v1.UpdateNativeEndpointPreferencesRequest]) (*connect.Response[v1.UpdateNativeEndpointPreferencesResponse], error)
}

func NewNativeNotificationServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) NativeNotificationServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	nativeNotificationServiceMethods := v1.File_chatto_api_v1_native_notifications_proto.Services().ByName("NativeNotificationService").Methods()
	return &nativeNotificationServiceClient{
		getNativeNotificationConfig: connect.NewClient[v1.GetNativeNotificationConfigRequest, v1.GetNativeNotificationConfigResponse](httpClient, baseURL+NativeNotificationServiceGetNativeNotificationConfigProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("GetNativeNotificationConfig")), connect.WithClientOptions(opts...)),
		registerNativeEndpoint: connect.NewClient[v1.RegisterNativeEndpointRequest, v1.RegisterNativeEndpointResponse](httpClient, baseURL+NativeNotificationServiceRegisterNativeEndpointProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("RegisterNativeEndpoint")), connect.WithClientOptions(opts...)),
		rotateNativeEndpoint: connect.NewClient[v1.RotateNativeEndpointRequest, v1.RotateNativeEndpointResponse](httpClient, baseURL+NativeNotificationServiceRotateNativeEndpointProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("RotateNativeEndpoint")), connect.WithClientOptions(opts...)),
		unregisterNativeEndpoint: connect.NewClient[v1.UnregisterNativeEndpointRequest, v1.UnregisterNativeEndpointResponse](httpClient, baseURL+NativeNotificationServiceUnregisterNativeEndpointProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("UnregisterNativeEndpoint")), connect.WithClientOptions(opts...)),
		listNativeEndpoints: connect.NewClient[v1.ListNativeEndpointsRequest, v1.ListNativeEndpointsResponse](httpClient, baseURL+NativeNotificationServiceListNativeEndpointsProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("ListNativeEndpoints")), connect.WithClientOptions(opts...)),
		updateNativeEndpointPreferences: connect.NewClient[v1.UpdateNativeEndpointPreferencesRequest, v1.UpdateNativeEndpointPreferencesResponse](httpClient, baseURL+NativeNotificationServiceUpdateNativeEndpointPreferencesProcedure, connect.WithSchema(nativeNotificationServiceMethods.ByName("UpdateNativeEndpointPreferences")), connect.WithClientOptions(opts...)),
	}
}

type nativeNotificationServiceClient struct {
	getNativeNotificationConfig *connect.Client[v1.GetNativeNotificationConfigRequest, v1.GetNativeNotificationConfigResponse]
	registerNativeEndpoint *connect.Client[v1.RegisterNativeEndpointRequest, v1.RegisterNativeEndpointResponse]
	rotateNativeEndpoint *connect.Client[v1.RotateNativeEndpointRequest, v1.RotateNativeEndpointResponse]
	unregisterNativeEndpoint *connect.Client[v1.UnregisterNativeEndpointRequest, v1.UnregisterNativeEndpointResponse]
	listNativeEndpoints *connect.Client[v1.ListNativeEndpointsRequest, v1.ListNativeEndpointsResponse]
	updateNativeEndpointPreferences *connect.Client[v1.UpdateNativeEndpointPreferencesRequest, v1.UpdateNativeEndpointPreferencesResponse]
}

func (c *nativeNotificationServiceClient) GetNativeNotificationConfig(ctx context.Context, req *connect.Request[v1.GetNativeNotificationConfigRequest]) (*connect.Response[v1.GetNativeNotificationConfigResponse], error) { return c.getNativeNotificationConfig.CallUnary(ctx, req) }
func (c *nativeNotificationServiceClient) RegisterNativeEndpoint(ctx context.Context, req *connect.Request[v1.RegisterNativeEndpointRequest]) (*connect.Response[v1.RegisterNativeEndpointResponse], error) { return c.registerNativeEndpoint.CallUnary(ctx, req) }
func (c *nativeNotificationServiceClient) RotateNativeEndpoint(ctx context.Context, req *connect.Request[v1.RotateNativeEndpointRequest]) (*connect.Response[v1.RotateNativeEndpointResponse], error) { return c.rotateNativeEndpoint.CallUnary(ctx, req) }
func (c *nativeNotificationServiceClient) UnregisterNativeEndpoint(ctx context.Context, req *connect.Request[v1.UnregisterNativeEndpointRequest]) (*connect.Response[v1.UnregisterNativeEndpointResponse], error) { return c.unregisterNativeEndpoint.CallUnary(ctx, req) }
func (c *nativeNotificationServiceClient) ListNativeEndpoints(ctx context.Context, req *connect.Request[v1.ListNativeEndpointsRequest]) (*connect.Response[v1.ListNativeEndpointsResponse], error) { return c.listNativeEndpoints.CallUnary(ctx, req) }
func (c *nativeNotificationServiceClient) UpdateNativeEndpointPreferences(ctx context.Context, req *connect.Request[v1.UpdateNativeEndpointPreferencesRequest]) (*connect.Response[v1.UpdateNativeEndpointPreferencesResponse], error) { return c.updateNativeEndpointPreferences.CallUnary(ctx, req) }

type NativeNotificationServiceHandler interface {
	GetNativeNotificationConfig(context.Context, *connect.Request[v1.GetNativeNotificationConfigRequest]) (*connect.Response[v1.GetNativeNotificationConfigResponse], error)
	RegisterNativeEndpoint(context.Context, *connect.Request[v1.RegisterNativeEndpointRequest]) (*connect.Response[v1.RegisterNativeEndpointResponse], error)
	RotateNativeEndpoint(context.Context, *connect.Request[v1.RotateNativeEndpointRequest]) (*connect.Response[v1.RotateNativeEndpointResponse], error)
	UnregisterNativeEndpoint(context.Context, *connect.Request[v1.UnregisterNativeEndpointRequest]) (*connect.Response[v1.UnregisterNativeEndpointResponse], error)
	ListNativeEndpoints(context.Context, *connect.Request[v1.ListNativeEndpointsRequest]) (*connect.Response[v1.ListNativeEndpointsResponse], error)
	UpdateNativeEndpointPreferences(context.Context, *connect.Request[v1.UpdateNativeEndpointPreferencesRequest]) (*connect.Response[v1.UpdateNativeEndpointPreferencesResponse], error)
}

func NewNativeNotificationServiceHandler(svc NativeNotificationServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	nativeNotificationServiceMethods := v1.File_chatto_api_v1_native_notifications_proto.Services().ByName("NativeNotificationService").Methods()
	getNativeNotificationConfig := connect.NewUnaryHandler(NativeNotificationServiceGetNativeNotificationConfigProcedure, svc.GetNativeNotificationConfig, connect.WithSchema(nativeNotificationServiceMethods.ByName("GetNativeNotificationConfig")), connect.WithHandlerOptions(opts...))
	registerNativeEndpoint := connect.NewUnaryHandler(NativeNotificationServiceRegisterNativeEndpointProcedure, svc.RegisterNativeEndpoint, connect.WithSchema(nativeNotificationServiceMethods.ByName("RegisterNativeEndpoint")), connect.WithHandlerOptions(opts...))
	rotateNativeEndpoint := connect.NewUnaryHandler(NativeNotificationServiceRotateNativeEndpointProcedure, svc.RotateNativeEndpoint, connect.WithSchema(nativeNotificationServiceMethods.ByName("RotateNativeEndpoint")), connect.WithHandlerOptions(opts...))
	unregisterNativeEndpoint := connect.NewUnaryHandler(NativeNotificationServiceUnregisterNativeEndpointProcedure, svc.UnregisterNativeEndpoint, connect.WithSchema(nativeNotificationServiceMethods.ByName("UnregisterNativeEndpoint")), connect.WithHandlerOptions(opts...))
	listNativeEndpoints := connect.NewUnaryHandler(NativeNotificationServiceListNativeEndpointsProcedure, svc.ListNativeEndpoints, connect.WithSchema(nativeNotificationServiceMethods.ByName("ListNativeEndpoints")), connect.WithHandlerOptions(opts...))
	updateNativeEndpointPreferences := connect.NewUnaryHandler(NativeNotificationServiceUpdateNativeEndpointPreferencesProcedure, svc.UpdateNativeEndpointPreferences, connect.WithSchema(nativeNotificationServiceMethods.ByName("UpdateNativeEndpointPreferences")), connect.WithHandlerOptions(opts...))
	return "/chatto.api.v1.NativeNotificationService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case NativeNotificationServiceGetNativeNotificationConfigProcedure:
			getNativeNotificationConfig.ServeHTTP(w, r)
		case NativeNotificationServiceRegisterNativeEndpointProcedure:
			registerNativeEndpoint.ServeHTTP(w, r)
		case NativeNotificationServiceRotateNativeEndpointProcedure:
			rotateNativeEndpoint.ServeHTTP(w, r)
		case NativeNotificationServiceUnregisterNativeEndpointProcedure:
			unregisterNativeEndpoint.ServeHTTP(w, r)
		case NativeNotificationServiceListNativeEndpointsProcedure:
			listNativeEndpoints.ServeHTTP(w, r)
		case NativeNotificationServiceUpdateNativeEndpointPreferencesProcedure:
			updateNativeEndpointPreferences.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

type UnimplementedNativeNotificationServiceHandler struct{}

func (UnimplementedNativeNotificationServiceHandler) GetNativeNotificationConfig(context.Context, *connect.Request[v1.GetNativeNotificationConfigRequest]) (*connect.Response[v1.GetNativeNotificationConfigResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.GetNativeNotificationConfig is not implemented")) }
func (UnimplementedNativeNotificationServiceHandler) RegisterNativeEndpoint(context.Context, *connect.Request[v1.RegisterNativeEndpointRequest]) (*connect.Response[v1.RegisterNativeEndpointResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.RegisterNativeEndpoint is not implemented")) }
func (UnimplementedNativeNotificationServiceHandler) RotateNativeEndpoint(context.Context, *connect.Request[v1.RotateNativeEndpointRequest]) (*connect.Response[v1.RotateNativeEndpointResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.RotateNativeEndpoint is not implemented")) }
func (UnimplementedNativeNotificationServiceHandler) UnregisterNativeEndpoint(context.Context, *connect.Request[v1.UnregisterNativeEndpointRequest]) (*connect.Response[v1.UnregisterNativeEndpointResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.UnregisterNativeEndpoint is not implemented")) }
func (UnimplementedNativeNotificationServiceHandler) ListNativeEndpoints(context.Context, *connect.Request[v1.ListNativeEndpointsRequest]) (*connect.Response[v1.ListNativeEndpointsResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.ListNativeEndpoints is not implemented")) }
func (UnimplementedNativeNotificationServiceHandler) UpdateNativeEndpointPreferences(context.Context, *connect.Request[v1.UpdateNativeEndpointPreferencesRequest]) (*connect.Response[v1.UpdateNativeEndpointPreferencesResponse], error) { return nil, connect.NewError(connect.CodeUnimplemented, errors.New("chatto.api.v1.NativeNotificationService.UpdateNativeEndpointPreferences is not implemented")) }
