// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: chatto/api/v1/native_notifications.proto

package apiv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Native clients outside the Android and Linux phase are reserved for forward
// compatibility and are rejected by the current server implementation.
type NativeNotificationPlatform int32

const (
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED NativeNotificationPlatform = 0
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_ANDROID     NativeNotificationPlatform = 1
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_LINUX       NativeNotificationPlatform = 2
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_WINDOWS     NativeNotificationPlatform = 3
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_MACOS       NativeNotificationPlatform = 4
	NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_IOS         NativeNotificationPlatform = 5
)

// Enum value maps for NativeNotificationPlatform.
var (
	NativeNotificationPlatform_name = map[int32]string{
		0: "NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED",
		1: "NATIVE_NOTIFICATION_PLATFORM_ANDROID",
		2: "NATIVE_NOTIFICATION_PLATFORM_LINUX",
		3: "NATIVE_NOTIFICATION_PLATFORM_WINDOWS",
		4: "NATIVE_NOTIFICATION_PLATFORM_MACOS",
		5: "NATIVE_NOTIFICATION_PLATFORM_IOS",
	}
	NativeNotificationPlatform_value = map[string]int32{
		"NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED": 0,
		"NATIVE_NOTIFICATION_PLATFORM_ANDROID":     1,
		"NATIVE_NOTIFICATION_PLATFORM_LINUX":       2,
		"NATIVE_NOTIFICATION_PLATFORM_WINDOWS":     3,
		"NATIVE_NOTIFICATION_PLATFORM_MACOS":       4,
		"NATIVE_NOTIFICATION_PLATFORM_IOS":         5,
	}
)

func (x NativeNotificationPlatform) Enum() *NativeNotificationPlatform {
	p := new(NativeNotificationPlatform)
	*p = x
	return p
}

func (x NativeNotificationPlatform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NativeNotificationPlatform) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_native_notifications_proto_enumTypes[0].Descriptor()
}

func (NativeNotificationPlatform) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_native_notifications_proto_enumTypes[0]
}

func (x NativeNotificationPlatform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NativeNotificationPlatform.Descriptor instead.
func (NativeNotificationPlatform) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{0}
}

type NativeNotificationTransport int32

const (
	NativeNotificationTransport_NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED NativeNotificationTransport = 0
	// Android wake signals sent through the Towk-operated FCM relay.
	NativeNotificationTransport_NATIVE_NOTIFICATION_TRANSPORT_ANDROID_MANAGED_FCM NativeNotificationTransport = 1
	// Linux notifications derived from the authenticated instance WebSocket.
	NativeNotificationTransport_NATIVE_NOTIFICATION_TRANSPORT_LINUX_RESIDENT_WEBSOCKET NativeNotificationTransport = 2
)

// Enum value maps for NativeNotificationTransport.
var (
	NativeNotificationTransport_name = map[int32]string{
		0: "NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED",
		1: "NATIVE_NOTIFICATION_TRANSPORT_ANDROID_MANAGED_FCM",
		2: "NATIVE_NOTIFICATION_TRANSPORT_LINUX_RESIDENT_WEBSOCKET",
	}
	NativeNotificationTransport_value = map[string]int32{
		"NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED":              0,
		"NATIVE_NOTIFICATION_TRANSPORT_ANDROID_MANAGED_FCM":      1,
		"NATIVE_NOTIFICATION_TRANSPORT_LINUX_RESIDENT_WEBSOCKET": 2,
	}
)

func (x NativeNotificationTransport) Enum() *NativeNotificationTransport {
	p := new(NativeNotificationTransport)
	*p = x
	return p
}

func (x NativeNotificationTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NativeNotificationTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_native_notifications_proto_enumTypes[1].Descriptor()
}

func (NativeNotificationTransport) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_native_notifications_proto_enumTypes[1]
}

func (x NativeNotificationTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NativeNotificationTransport.Descriptor instead.
func (NativeNotificationTransport) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{1}
}

type NativeEndpointState int32

const (
	NativeEndpointState_NATIVE_ENDPOINT_STATE_UNSPECIFIED         NativeEndpointState = 0
	NativeEndpointState_NATIVE_ENDPOINT_STATE_ACTIVE              NativeEndpointState = 1
	NativeEndpointState_NATIVE_ENDPOINT_STATE_DISABLED            NativeEndpointState = 2
	NativeEndpointState_NATIVE_ENDPOINT_STATE_PERMANENTLY_INVALID NativeEndpointState = 3
)

// Enum value maps for NativeEndpointState.
var (
	NativeEndpointState_name = map[int32]string{
		0: "NATIVE_ENDPOINT_STATE_UNSPECIFIED",
		1: "NATIVE_ENDPOINT_STATE_ACTIVE",
		2: "NATIVE_ENDPOINT_STATE_DISABLED",
		3: "NATIVE_ENDPOINT_STATE_PERMANENTLY_INVALID",
	}
	NativeEndpointState_value = map[string]int32{
		"NATIVE_ENDPOINT_STATE_UNSPECIFIED":         0,
		"NATIVE_ENDPOINT_STATE_ACTIVE":              1,
		"NATIVE_ENDPOINT_STATE_DISABLED":            2,
		"NATIVE_ENDPOINT_STATE_PERMANENTLY_INVALID": 3,
	}
)

func (x NativeEndpointState) Enum() *NativeEndpointState {
	p := new(NativeEndpointState)
	*p = x
	return p
}

func (x NativeEndpointState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NativeEndpointState) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_native_notifications_proto_enumTypes[2].Descriptor()
}

func (NativeEndpointState) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_native_notifications_proto_enumTypes[2]
}

func (x NativeEndpointState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NativeEndpointState.Descriptor instead.
func (NativeEndpointState) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{2}
}

type NativeDeliveryStatus int32

const (
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_UNSPECIFIED            NativeDeliveryStatus = 0
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_NEVER_ATTEMPTED        NativeDeliveryStatus = 1
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_PENDING                NativeDeliveryStatus = 2
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_DELIVERED_TO_TRANSPORT NativeDeliveryStatus = 3
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_RETRYABLE_FAILURE      NativeDeliveryStatus = 4
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_EXPIRED                NativeDeliveryStatus = 5
	NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_PERMANENTLY_INVALID    NativeDeliveryStatus = 6
)

// Enum value maps for NativeDeliveryStatus.
var (
	NativeDeliveryStatus_name = map[int32]string{
		0: "NATIVE_DELIVERY_STATUS_UNSPECIFIED",
		1: "NATIVE_DELIVERY_STATUS_NEVER_ATTEMPTED",
		2: "NATIVE_DELIVERY_STATUS_PENDING",
		3: "NATIVE_DELIVERY_STATUS_DELIVERED_TO_TRANSPORT",
		4: "NATIVE_DELIVERY_STATUS_RETRYABLE_FAILURE",
		5: "NATIVE_DELIVERY_STATUS_EXPIRED",
		6: "NATIVE_DELIVERY_STATUS_PERMANENTLY_INVALID",
	}
	NativeDeliveryStatus_value = map[string]int32{
		"NATIVE_DELIVERY_STATUS_UNSPECIFIED":            0,
		"NATIVE_DELIVERY_STATUS_NEVER_ATTEMPTED":        1,
		"NATIVE_DELIVERY_STATUS_PENDING":                2,
		"NATIVE_DELIVERY_STATUS_DELIVERED_TO_TRANSPORT": 3,
		"NATIVE_DELIVERY_STATUS_RETRYABLE_FAILURE":      4,
		"NATIVE_DELIVERY_STATUS_EXPIRED":                5,
		"NATIVE_DELIVERY_STATUS_PERMANENTLY_INVALID":    6,
	}
)

func (x NativeDeliveryStatus) Enum() *NativeDeliveryStatus {
	p := new(NativeDeliveryStatus)
	*p = x
	return p
}

func (x NativeDeliveryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NativeDeliveryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_chatto_api_v1_native_notifications_proto_enumTypes[3].Descriptor()
}

func (NativeDeliveryStatus) Type() protoreflect.EnumType {
	return &file_chatto_api_v1_native_notifications_proto_enumTypes[3]
}

func (x NativeDeliveryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NativeDeliveryStatus.Descriptor instead.
func (NativeDeliveryStatus) EnumDescriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{3}
}

type GetNativeNotificationConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNativeNotificationConfigRequest) Reset() {
	*x = GetNativeNotificationConfigRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNativeNotificationConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNativeNotificationConfigRequest) ProtoMessage() {}

func (x *GetNativeNotificationConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNativeNotificationConfigRequest.ProtoReflect.Descriptor instead.
func (*GetNativeNotificationConfigRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{0}
}

type GetNativeNotificationConfigResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Enabled                       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	AndroidManagedFcmEnabled      bool                   `protobuf:"varint,2,opt,name=android_managed_fcm_enabled,json=androidManagedFcmEnabled,proto3" json:"android_managed_fcm_enabled,omitempty"`
	LinuxResidentWebsocketEnabled bool                   `protobuf:"varint,3,opt,name=linux_resident_websocket_enabled,json=linuxResidentWebsocketEnabled,proto3" json:"linux_resident_websocket_enabled,omitempty"`
	ManagedFcmRelayUrl            string                 `protobuf:"bytes,4,opt,name=managed_fcm_relay_url,json=managedFcmRelayUrl,proto3" json:"managed_fcm_relay_url,omitempty"`
	SignalEncryptionSuite         string                 `protobuf:"bytes,5,opt,name=signal_encryption_suite,json=signalEncryptionSuite,proto3" json:"signal_encryption_suite,omitempty"`
	MaxSignalBytes                uint32                 `protobuf:"varint,6,opt,name=max_signal_bytes,json=maxSignalBytes,proto3" json:"max_signal_bytes,omitempty"`
	MaxSignalAgeSeconds           uint32                 `protobuf:"varint,7,opt,name=max_signal_age_seconds,json=maxSignalAgeSeconds,proto3" json:"max_signal_age_seconds,omitempty"`
	ManagedFcmEnrollmentState     string                 `protobuf:"bytes,8,opt,name=managed_fcm_enrollment_state,json=managedFcmEnrollmentState,proto3" json:"managed_fcm_enrollment_state,omitempty"`
	ManagedFcmInstanceId          string                 `protobuf:"bytes,9,opt,name=managed_fcm_instance_id,json=managedFcmInstanceId,proto3" json:"managed_fcm_instance_id,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GetNativeNotificationConfigResponse) Reset() {
	*x = GetNativeNotificationConfigResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNativeNotificationConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNativeNotificationConfigResponse) ProtoMessage() {}

func (x *GetNativeNotificationConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNativeNotificationConfigResponse.ProtoReflect.Descriptor instead.
func (*GetNativeNotificationConfigResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *GetNativeNotificationConfigResponse) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *GetNativeNotificationConfigResponse) GetAndroidManagedFcmEnabled() bool {
	if x != nil {
		return x.AndroidManagedFcmEnabled
	}
	return false
}

func (x *GetNativeNotificationConfigResponse) GetLinuxResidentWebsocketEnabled() bool {
	if x != nil {
		return x.LinuxResidentWebsocketEnabled
	}
	return false
}

func (x *GetNativeNotificationConfigResponse) GetManagedFcmRelayUrl() string {
	if x != nil {
		return x.ManagedFcmRelayUrl
	}
	return ""
}

func (x *GetNativeNotificationConfigResponse) GetSignalEncryptionSuite() string {
	if x != nil {
		return x.SignalEncryptionSuite
	}
	return ""
}

func (x *GetNativeNotificationConfigResponse) GetMaxSignalBytes() uint32 {
	if x != nil {
		return x.MaxSignalBytes
	}
	return 0
}

func (x *GetNativeNotificationConfigResponse) GetMaxSignalAgeSeconds() uint32 {
	if x != nil {
		return x.MaxSignalAgeSeconds
	}
	return 0
}

func (x *GetNativeNotificationConfigResponse) GetManagedFcmEnrollmentState() string {
	if x != nil {
		return x.ManagedFcmEnrollmentState
	}
	return ""
}

func (x *GetNativeNotificationConfigResponse) GetManagedFcmInstanceId() string {
	if x != nil {
		return x.ManagedFcmInstanceId
	}
	return ""
}

type EnrollManagedFCMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollManagedFCMRequest) Reset() {
	*x = EnrollManagedFCMRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollManagedFCMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollManagedFCMRequest) ProtoMessage() {}

func (x *EnrollManagedFCMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollManagedFCMRequest.ProtoReflect.Descriptor instead.
func (*EnrollManagedFCMRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{2}
}

type EnrollManagedFCMResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentState string                 `protobuf:"bytes,1,opt,name=enrollment_state,json=enrollmentState,proto3" json:"enrollment_state,omitempty"`
	InstanceId      string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EnrollManagedFCMResponse) Reset() {
	*x = EnrollManagedFCMResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollManagedFCMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollManagedFCMResponse) ProtoMessage() {}

func (x *EnrollManagedFCMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollManagedFCMResponse.ProtoReflect.Descriptor instead.
func (*EnrollManagedFCMResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *EnrollManagedFCMResponse) GetEnrollmentState() string {
	if x != nil {
		return x.EnrollmentState
	}
	return ""
}

func (x *EnrollManagedFCMResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type NativeEndpointPreferences struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Messages      bool                   `protobuf:"varint,2,opt,name=messages,proto3" json:"messages,omitempty"`
	Calls         bool                   `protobuf:"varint,3,opt,name=calls,proto3" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeEndpointPreferences) Reset() {
	*x = NativeEndpointPreferences{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeEndpointPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeEndpointPreferences) ProtoMessage() {}

func (x *NativeEndpointPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeEndpointPreferences.ProtoReflect.Descriptor instead.
func (*NativeEndpointPreferences) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *NativeEndpointPreferences) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NativeEndpointPreferences) GetMessages() bool {
	if x != nil {
		return x.Messages
	}
	return false
}

func (x *NativeEndpointPreferences) GetCalls() bool {
	if x != nil {
		return x.Calls
	}
	return false
}

type NativeEndpointPreferencesPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Messages      *bool                  `protobuf:"varint,2,opt,name=messages,proto3,oneof" json:"messages,omitempty"`
	Calls         *bool                  `protobuf:"varint,3,opt,name=calls,proto3,oneof" json:"calls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NativeEndpointPreferencesPatch) Reset() {
	*x = NativeEndpointPreferencesPatch{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeEndpointPreferencesPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeEndpointPreferencesPatch) ProtoMessage() {}

func (x *NativeEndpointPreferencesPatch) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeEndpointPreferencesPatch.ProtoReflect.Descriptor instead.
func (*NativeEndpointPreferencesPatch) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *NativeEndpointPreferencesPatch) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *NativeEndpointPreferencesPatch) GetMessages() bool {
	if x != nil && x.Messages != nil {
		return *x.Messages
	}
	return false
}

func (x *NativeEndpointPreferencesPatch) GetCalls() bool {
	if x != nil && x.Calls != nil {
		return *x.Calls
	}
	return false
}

type NativeEndpoint struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	EndpointId     string                      `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	InstallationId string                      `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Platform       NativeNotificationPlatform  `protobuf:"varint,3,opt,name=platform,proto3,enum=chatto.api.v1.NativeNotificationPlatform" json:"platform,omitempty"`
	Transport      NativeNotificationTransport `protobuf:"varint,4,opt,name=transport,proto3,enum=chatto.api.v1.NativeNotificationTransport" json:"transport,omitempty"`
	AppId          string                      `protobuf:"bytes,5,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	// Present only for the endpoint owner. Never written to logs.
	FcmInstallationId string `protobuf:"bytes,6,opt,name=fcm_installation_id,json=fcmInstallationId,proto3" json:"fcm_installation_id,omitempty"`
	// Public installation encryption key. The private key stays on the client.
	ClientPublicKey    []byte                     `protobuf:"bytes,7,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Locale             string                     `protobuf:"bytes,8,opt,name=locale,proto3" json:"locale,omitempty"`
	CreatedAt          *timestamppb.Timestamp     `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LastSeenAt         *timestamppb.Timestamp     `protobuf:"bytes,10,opt,name=last_seen_at,json=lastSeenAt,proto3" json:"last_seen_at,omitempty"`
	DisabledAt         *timestamppb.Timestamp     `protobuf:"bytes,11,opt,name=disabled_at,json=disabledAt,proto3" json:"disabled_at,omitempty"`
	State              NativeEndpointState        `protobuf:"varint,12,opt,name=state,proto3,enum=chatto.api.v1.NativeEndpointState" json:"state,omitempty"`
	LastDeliveryStatus NativeDeliveryStatus       `protobuf:"varint,13,opt,name=last_delivery_status,json=lastDeliveryStatus,proto3,enum=chatto.api.v1.NativeDeliveryStatus" json:"last_delivery_status,omitempty"`
	Preferences        *NativeEndpointPreferences `protobuf:"bytes,14,opt,name=preferences,proto3" json:"preferences,omitempty"`
	Generation         uint64                     `protobuf:"varint,15,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NativeEndpoint) Reset() {
	*x = NativeEndpoint{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NativeEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NativeEndpoint) ProtoMessage() {}

func (x *NativeEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NativeEndpoint.ProtoReflect.Descriptor instead.
func (*NativeEndpoint) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *NativeEndpoint) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *NativeEndpoint) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *NativeEndpoint) GetPlatform() NativeNotificationPlatform {
	if x != nil {
		return x.Platform
	}
	return NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED
}

func (x *NativeEndpoint) GetTransport() NativeNotificationTransport {
	if x != nil {
		return x.Transport
	}
	return NativeNotificationTransport_NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED
}

func (x *NativeEndpoint) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *NativeEndpoint) GetFcmInstallationId() string {
	if x != nil {
		return x.FcmInstallationId
	}
	return ""
}

func (x *NativeEndpoint) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *NativeEndpoint) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *NativeEndpoint) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NativeEndpoint) GetLastSeenAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeenAt
	}
	return nil
}

func (x *NativeEndpoint) GetDisabledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DisabledAt
	}
	return nil
}

func (x *NativeEndpoint) GetState() NativeEndpointState {
	if x != nil {
		return x.State
	}
	return NativeEndpointState_NATIVE_ENDPOINT_STATE_UNSPECIFIED
}

func (x *NativeEndpoint) GetLastDeliveryStatus() NativeDeliveryStatus {
	if x != nil {
		return x.LastDeliveryStatus
	}
	return NativeDeliveryStatus_NATIVE_DELIVERY_STATUS_UNSPECIFIED
}

func (x *NativeEndpoint) GetPreferences() *NativeEndpointPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

func (x *NativeEndpoint) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type RegisterNativeEndpointRequest struct {
	state             protoimpl.MessageState          `protogen:"open.v1"`
	InstallationId    string                          `protobuf:"bytes,1,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	Platform          NativeNotificationPlatform      `protobuf:"varint,2,opt,name=platform,proto3,enum=chatto.api.v1.NativeNotificationPlatform" json:"platform,omitempty"`
	Transport         NativeNotificationTransport     `protobuf:"varint,3,opt,name=transport,proto3,enum=chatto.api.v1.NativeNotificationTransport" json:"transport,omitempty"`
	AppId             string                          `protobuf:"bytes,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	FcmInstallationId string                          `protobuf:"bytes,5,opt,name=fcm_installation_id,json=fcmInstallationId,proto3" json:"fcm_installation_id,omitempty"`
	ClientPublicKey   []byte                          `protobuf:"bytes,6,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Locale            string                          `protobuf:"bytes,7,opt,name=locale,proto3" json:"locale,omitempty"`
	Preferences       *NativeEndpointPreferencesPatch `protobuf:"bytes,8,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterNativeEndpointRequest) Reset() {
	*x = RegisterNativeEndpointRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNativeEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNativeEndpointRequest) ProtoMessage() {}

func (x *RegisterNativeEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNativeEndpointRequest.ProtoReflect.Descriptor instead.
func (*RegisterNativeEndpointRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterNativeEndpointRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *RegisterNativeEndpointRequest) GetPlatform() NativeNotificationPlatform {
	if x != nil {
		return x.Platform
	}
	return NativeNotificationPlatform_NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED
}

func (x *RegisterNativeEndpointRequest) GetTransport() NativeNotificationTransport {
	if x != nil {
		return x.Transport
	}
	return NativeNotificationTransport_NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED
}

func (x *RegisterNativeEndpointRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RegisterNativeEndpointRequest) GetFcmInstallationId() string {
	if x != nil {
		return x.FcmInstallationId
	}
	return ""
}

func (x *RegisterNativeEndpointRequest) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *RegisterNativeEndpointRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *RegisterNativeEndpointRequest) GetPreferences() *NativeEndpointPreferencesPatch {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type RegisterNativeEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *NativeEndpoint        `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNativeEndpointResponse) Reset() {
	*x = RegisterNativeEndpointResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNativeEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNativeEndpointResponse) ProtoMessage() {}

func (x *RegisterNativeEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNativeEndpointResponse.ProtoReflect.Descriptor instead.
func (*RegisterNativeEndpointResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterNativeEndpointResponse) GetEndpoint() *NativeEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type RotateNativeEndpointRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EndpointId         string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ExpectedGeneration uint64                 `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	FcmInstallationId  string                 `protobuf:"bytes,3,opt,name=fcm_installation_id,json=fcmInstallationId,proto3" json:"fcm_installation_id,omitempty"`
	ClientPublicKey    []byte                 `protobuf:"bytes,4,opt,name=client_public_key,json=clientPublicKey,proto3" json:"client_public_key,omitempty"`
	Locale             string                 `protobuf:"bytes,5,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RotateNativeEndpointRequest) Reset() {
	*x = RotateNativeEndpointRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNativeEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNativeEndpointRequest) ProtoMessage() {}

func (x *RotateNativeEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNativeEndpointRequest.ProtoReflect.Descriptor instead.
func (*RotateNativeEndpointRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *RotateNativeEndpointRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *RotateNativeEndpointRequest) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

func (x *RotateNativeEndpointRequest) GetFcmInstallationId() string {
	if x != nil {
		return x.FcmInstallationId
	}
	return ""
}

func (x *RotateNativeEndpointRequest) GetClientPublicKey() []byte {
	if x != nil {
		return x.ClientPublicKey
	}
	return nil
}

func (x *RotateNativeEndpointRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type RotateNativeEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *NativeEndpoint        `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateNativeEndpointResponse) Reset() {
	*x = RotateNativeEndpointResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateNativeEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateNativeEndpointResponse) ProtoMessage() {}

func (x *RotateNativeEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateNativeEndpointResponse.ProtoReflect.Descriptor instead.
func (*RotateNativeEndpointResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *RotateNativeEndpointResponse) GetEndpoint() *NativeEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

type UnregisterNativeEndpointRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	EndpointId         string                 `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ExpectedGeneration uint64                 `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UnregisterNativeEndpointRequest) Reset() {
	*x = UnregisterNativeEndpointRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNativeEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNativeEndpointRequest) ProtoMessage() {}

func (x *UnregisterNativeEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNativeEndpointRequest.ProtoReflect.Descriptor instead.
func (*UnregisterNativeEndpointRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *UnregisterNativeEndpointRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *UnregisterNativeEndpointRequest) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

type UnregisterNativeEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Unregistered  bool                   `protobuf:"varint,1,opt,name=unregistered,proto3" json:"unregistered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterNativeEndpointResponse) Reset() {
	*x = UnregisterNativeEndpointResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterNativeEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterNativeEndpointResponse) ProtoMessage() {}

func (x *UnregisterNativeEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterNativeEndpointResponse.ProtoReflect.Descriptor instead.
func (*UnregisterNativeEndpointResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *UnregisterNativeEndpointResponse) GetUnregistered() bool {
	if x != nil {
		return x.Unregistered
	}
	return false
}

type ListNativeEndpointsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNativeEndpointsRequest) Reset() {
	*x = ListNativeEndpointsRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNativeEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNativeEndpointsRequest) ProtoMessage() {}

func (x *ListNativeEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNativeEndpointsRequest.ProtoReflect.Descriptor instead.
func (*ListNativeEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{13}
}

type ListNativeEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*NativeEndpoint      `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNativeEndpointsResponse) Reset() {
	*x = ListNativeEndpointsResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNativeEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNativeEndpointsResponse) ProtoMessage() {}

func (x *ListNativeEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNativeEndpointsResponse.ProtoReflect.Descriptor instead.
func (*ListNativeEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *ListNativeEndpointsResponse) GetEndpoints() []*NativeEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type UpdateNativeEndpointPreferencesRequest struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	EndpointId         string                          `protobuf:"bytes,1,opt,name=endpoint_id,json=endpointId,proto3" json:"endpoint_id,omitempty"`
	ExpectedGeneration uint64                          `protobuf:"varint,2,opt,name=expected_generation,json=expectedGeneration,proto3" json:"expected_generation,omitempty"`
	Preferences        *NativeEndpointPreferencesPatch `protobuf:"bytes,3,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateNativeEndpointPreferencesRequest) Reset() {
	*x = UpdateNativeEndpointPreferencesRequest{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNativeEndpointPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNativeEndpointPreferencesRequest) ProtoMessage() {}

func (x *UpdateNativeEndpointPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNativeEndpointPreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdateNativeEndpointPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateNativeEndpointPreferencesRequest) GetEndpointId() string {
	if x != nil {
		return x.EndpointId
	}
	return ""
}

func (x *UpdateNativeEndpointPreferencesRequest) GetExpectedGeneration() uint64 {
	if x != nil {
		return x.ExpectedGeneration
	}
	return 0
}

func (x *UpdateNativeEndpointPreferencesRequest) GetPreferences() *NativeEndpointPreferencesPatch {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdateNativeEndpointPreferencesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoint      *NativeEndpoint        `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNativeEndpointPreferencesResponse) Reset() {
	*x = UpdateNativeEndpointPreferencesResponse{}
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNativeEndpointPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNativeEndpointPreferencesResponse) ProtoMessage() {}

func (x *UpdateNativeEndpointPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatto_api_v1_native_notifications_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNativeEndpointPreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdateNativeEndpointPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_chatto_api_v1_native_notifications_proto_rawDescGZIP(), []int{16}
}

func (x *UpdateNativeEndpointPreferencesResponse) GetEndpoint() *NativeEndpoint {
	if x != nil {
		return x.Endpoint
	}
	return nil
}

var File_chatto_api_v1_native_notifications_proto protoreflect.FileDescriptor

const file_chatto_api_v1_native_notifications_proto_rawDesc = "" +
	"\n" +
	"(chatto/api/v1/native_notifications.proto\x12\rchatto.api.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\"GetNativeNotificationConfigRequest\"\x89\x04\n" +
	"#GetNativeNotificationConfigResponse\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12=\n" +
	"\x1bandroid_managed_fcm_enabled\x18\x02 \x01(\bR\x18androidManagedFcmEnabled\x12G\n" +
	" linux_resident_websocket_enabled\x18\x03 \x01(\bR\x1dlinuxResidentWebsocketEnabled\x121\n" +
	"\x15managed_fcm_relay_url\x18\x04 \x01(\tR\x12managedFcmRelayUrl\x126\n" +
	"\x17signal_encryption_suite\x18\x05 \x01(\tR\x15signalEncryptionSuite\x12(\n" +
	"\x10max_signal_bytes\x18\x06 \x01(\rR\x0emaxSignalBytes\x123\n" +
	"\x16max_signal_age_seconds\x18\a \x01(\rR\x13maxSignalAgeSeconds\x12?\n" +
	"\x1cmanaged_fcm_enrollment_state\x18\b \x01(\tR\x19managedFcmEnrollmentState\x125\n" +
	"\x17managed_fcm_instance_id\x18\t \x01(\tR\x14managedFcmInstanceId\"\x19\n" +
	"\x17EnrollManagedFCMRequest\"f\n" +
	"\x18EnrollManagedFCMResponse\x12)\n" +
	"\x10enrollment_state\x18\x01 \x01(\tR\x0fenrollmentState\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\"g\n" +
	"\x19NativeEndpointPreferences\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1a\n" +
	"\bmessages\x18\x02 \x01(\bR\bmessages\x12\x14\n" +
	"\x05calls\x18\x03 \x01(\bR\x05calls\"\x9e\x01\n" +
	"\x1eNativeEndpointPreferencesPatch\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x12\x1f\n" +
	"\bmessages\x18\x02 \x01(\bH\x01R\bmessages\x88\x01\x01\x12\x19\n" +
	"\x05calls\x18\x03 \x01(\bH\x02R\x05calls\x88\x01\x01B\n" +
	"\n" +
	"\b_enabledB\v\n" +
	"\t_messagesB\b\n" +
	"\x06_calls\"\xa9\x06\n" +
	"\x0eNativeEndpoint\x12\x1f\n" +
	"\vendpoint_id\x18\x01 \x01(\tR\n" +
	"endpointId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\tR\x0einstallationId\x12E\n" +
	"\bplatform\x18\x03 \x01(\x0e2).chatto.api.v1.NativeNotificationPlatformR\bplatform\x12H\n" +
	"\ttransport\x18\x04 \x01(\x0e2*.chatto.api.v1.NativeNotificationTransportR\ttransport\x12\x15\n" +
	"\x06app_id\x18\x05 \x01(\tR\x05appId\x12.\n" +
	"\x13fcm_installation_id\x18\x06 \x01(\tR\x11fcmInstallationId\x12*\n" +
	"\x11client_public_key\x18\a \x01(\fR\x0fclientPublicKey\x12\x16\n" +
	"\x06locale\x18\b \x01(\tR\x06locale\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12<\n" +
	"\flast_seen_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastSeenAt\x12;\n" +
	"\vdisabled_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"disabledAt\x128\n" +
	"\x05state\x18\f \x01(\x0e2\".chatto.api.v1.NativeEndpointStateR\x05state\x12U\n" +
	"\x14last_delivery_status\x18\r \x01(\x0e2#.chatto.api.v1.NativeDeliveryStatusR\x12lastDeliveryStatus\x12J\n" +
	"\vpreferences\x18\x0e \x01(\v2(.chatto.api.v1.NativeEndpointPreferencesR\vpreferences\x12\x1e\n" +
	"\n" +
	"generation\x18\x0f \x01(\x04R\n" +
	"generation\"\xb9\x04\n" +
	"\x1dRegisterNativeEndpointRequest\x12G\n" +
	"\x0finstallation_id\x18\x01 \x01(\tB\x1e\xbaH\x1br\x19\x10\x10\x18\x80\x012\x12^[A-Za-z0-9._~-]+$R\x0einstallationId\x12O\n" +
	"\bplatform\x18\x02 \x01(\x0e2).chatto.api.v1.NativeNotificationPlatformB\b\xbaH\x05\x82\x01\x02 \x00R\bplatform\x12R\n" +
	"\ttransport\x18\x03 \x01(\x0e2*.chatto.api.v1.NativeNotificationTransportB\b\xbaH\x05\x82\x01\x02 \x00R\ttransport\x124\n" +
	"\x06app_id\x18\x04 \x01(\tB\x1d\xbaH\x1ar\x18\x10\x01\x18\x80\x012\x11^[A-Za-z0-9._-]+$R\x05appId\x12L\n" +
	"\x13fcm_installation_id\x18\x05 \x01(\tB\x1c\xbaH\x19r\x17\x10\x14\x18\x80\x012\x10^[A-Za-z0-9_-]+$R\x11fcmInstallationId\x124\n" +
	"\x11client_public_key\x18\x06 \x01(\fB\b\xbaH\x05z\x03\x18\x80\x02R\x0fclientPublicKey\x12\x1f\n" +
	"\x06locale\x18\a \x01(\tB\a\xbaH\x04r\x02\x18\x10R\x06locale\x12O\n" +
	"\vpreferences\x18\b \x01(\v2-.chatto.api.v1.NativeEndpointPreferencesPatchR\vpreferences\"[\n" +
	"\x1eRegisterNativeEndpointResponse\x129\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1d.chatto.api.v1.NativeEndpointR\bendpoint\"\xbc\x02\n" +
	"\x1bRotateNativeEndpointRequest\x12<\n" +
	"\vendpoint_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x10\x18@2\x10^[A-Za-z0-9_-]+$R\n" +
	"endpointId\x128\n" +
	"\x13expected_generation\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x12expectedGeneration\x12L\n" +
	"\x13fcm_installation_id\x18\x03 \x01(\tB\x1c\xbaH\x19r\x17\x10\x14\x18\x80\x012\x10^[A-Za-z0-9_-]+$R\x11fcmInstallationId\x126\n" +
	"\x11client_public_key\x18\x04 \x01(\fB\n" +
	"\xbaH\az\x05\x10\x01\x18\x80\x02R\x0fclientPublicKey\x12\x1f\n" +
	"\x06locale\x18\x05 \x01(\tB\a\xbaH\x04r\x02\x18\x10R\x06locale\"Y\n" +
	"\x1cRotateNativeEndpointResponse\x129\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1d.chatto.api.v1.NativeEndpointR\bendpoint\"\x99\x01\n" +
	"\x1fUnregisterNativeEndpointRequest\x12<\n" +
	"\vendpoint_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x10\x18@2\x10^[A-Za-z0-9_-]+$R\n" +
	"endpointId\x128\n" +
	"\x13expected_generation\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x12expectedGeneration\"F\n" +
	" UnregisterNativeEndpointResponse\x12\"\n" +
	"\funregistered\x18\x01 \x01(\bR\funregistered\"\x1c\n" +
	"\x1aListNativeEndpointsRequest\"Z\n" +
	"\x1bListNativeEndpointsResponse\x12;\n" +
	"\tendpoints\x18\x01 \x03(\v2\x1d.chatto.api.v1.NativeEndpointR\tendpoints\"\xf9\x01\n" +
	"&UpdateNativeEndpointPreferencesRequest\x12<\n" +
	"\vendpoint_id\x18\x01 \x01(\tB\x1b\xbaH\x18r\x16\x10\x10\x18@2\x10^[A-Za-z0-9_-]+$R\n" +
	"endpointId\x128\n" +
	"\x13expected_generation\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x12expectedGeneration\x12W\n" +
	"\vpreferences\x18\x03 \x01(\v2-.chatto.api.v1.NativeEndpointPreferencesPatchB\x06\xbaH\x03\xc8\x01\x01R\vpreferences\"d\n" +
	"'UpdateNativeEndpointPreferencesResponse\x129\n" +
	"\bendpoint\x18\x01 \x01(\v2\x1d.chatto.api.v1.NativeEndpointR\bendpoint*\x94\x02\n" +
	"\x1aNativeNotificationPlatform\x12,\n" +
	"(NATIVE_NOTIFICATION_PLATFORM_UNSPECIFIED\x10\x00\x12(\n" +
	"$NATIVE_NOTIFICATION_PLATFORM_ANDROID\x10\x01\x12&\n" +
	"\"NATIVE_NOTIFICATION_PLATFORM_LINUX\x10\x02\x12(\n" +
	"$NATIVE_NOTIFICATION_PLATFORM_WINDOWS\x10\x03\x12&\n" +
	"\"NATIVE_NOTIFICATION_PLATFORM_MACOS\x10\x04\x12$\n" +
	" NATIVE_NOTIFICATION_PLATFORM_IOS\x10\x05*\xbf\x01\n" +
	"\x1bNativeNotificationTransport\x12-\n" +
	")NATIVE_NOTIFICATION_TRANSPORT_UNSPECIFIED\x10\x00\x125\n" +
	"1NATIVE_NOTIFICATION_TRANSPORT_ANDROID_MANAGED_FCM\x10\x01\x12:\n" +
	"6NATIVE_NOTIFICATION_TRANSPORT_LINUX_RESIDENT_WEBSOCKET\x10\x02*\xb1\x01\n" +
	"\x13NativeEndpointState\x12%\n" +
	"!NATIVE_ENDPOINT_STATE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cNATIVE_ENDPOINT_STATE_ACTIVE\x10\x01\x12\"\n" +
	"\x1eNATIVE_ENDPOINT_STATE_DISABLED\x10\x02\x12-\n" +
	")NATIVE_ENDPOINT_STATE_PERMANENTLY_INVALID\x10\x03*\xc3\x02\n" +
	"\x14NativeDeliveryStatus\x12&\n" +
	"\"NATIVE_DELIVERY_STATUS_UNSPECIFIED\x10\x00\x12*\n" +
	"&NATIVE_DELIVERY_STATUS_NEVER_ATTEMPTED\x10\x01\x12\"\n" +
	"\x1eNATIVE_DELIVERY_STATUS_PENDING\x10\x02\x121\n" +
	"-NATIVE_DELIVERY_STATUS_DELIVERED_TO_TRANSPORT\x10\x03\x12,\n" +
	"(NATIVE_DELIVERY_STATUS_RETRYABLE_FAILURE\x10\x04\x12\"\n" +
	"\x1eNATIVE_DELIVERY_STATUS_EXPIRED\x10\x05\x12.\n" +
	"*NATIVE_DELIVERY_STATUS_PERMANENTLY_INVALID\x10\x062\xed\x06\n" +
	"\x19NativeNotificationService\x12\x84\x01\n" +
	"\x1bGetNativeNotificationConfig\x121.chatto.api.v1.GetNativeNotificationConfigRequest\x1a2.chatto.api.v1.GetNativeNotificationConfigResponse\x12c\n" +
	"\x10EnrollManagedFCM\x12&.chatto.api.v1.EnrollManagedFCMRequest\x1a'.chatto.api.v1.EnrollManagedFCMResponse\x12u\n" +
	"\x16RegisterNativeEndpoint\x12,.chatto.api.v1.RegisterNativeEndpointRequest\x1a-.chatto.api.v1.RegisterNativeEndpointResponse\x12o\n" +
	"\x14RotateNativeEndpoint\x12*.chatto.api.v1.RotateNativeEndpointRequest\x1a+.chatto.api.v1.RotateNativeEndpointResponse\x12{\n" +
	"\x18UnregisterNativeEndpoint\x12..chatto.api.v1.UnregisterNativeEndpointRequest\x1a/.chatto.api.v1.UnregisterNativeEndpointResponse\x12l\n" +
	"\x13ListNativeEndpoints\x12).chatto.api.v1.ListNativeEndpointsRequest\x1a*.chatto.api.v1.ListNativeEndpointsResponse\x12\x90\x01\n" +
	"\x1fUpdateNativeEndpointPreferences\x125.chatto.api.v1.UpdateNativeEndpointPreferencesRequest\x1a6.chatto.api.v1.UpdateNativeEndpointPreferencesResponseB\xb4\x01\n" +
	"\x11com.chatto.api.v1B\x18NativeNotificationsProtoP\x01Z/hmans.de/chatto/internal/pb/chatto/api/v1;apiv1\xa2\x02\x03CAX\xaa\x02\rChatto.Api.V1\xca\x02\rChatto\\Api\\V1\xe2\x02\x19Chatto\\Api\\V1\\GPBMetadata\xea\x02\x0fChatto::Api::V1b\x06proto3"

var (
	file_chatto_api_v1_native_notifications_proto_rawDescOnce sync.Once
	file_chatto_api_v1_native_notifications_proto_rawDescData []byte
)

func file_chatto_api_v1_native_notifications_proto_rawDescGZIP() []byte {
	file_chatto_api_v1_native_notifications_proto_rawDescOnce.Do(func() {
		file_chatto_api_v1_native_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_chatto_api_v1_native_notifications_proto_rawDesc), len(file_chatto_api_v1_native_notifications_proto_rawDesc)))
	})
	return file_chatto_api_v1_native_notifications_proto_rawDescData
}

var file_chatto_api_v1_native_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_chatto_api_v1_native_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_chatto_api_v1_native_notifications_proto_goTypes = []any{
	(NativeNotificationPlatform)(0),                 // 0: chatto.api.v1.NativeNotificationPlatform
	(NativeNotificationTransport)(0),                // 1: chatto.api.v1.NativeNotificationTransport
	(NativeEndpointState)(0),                        // 2: chatto.api.v1.NativeEndpointState
	(NativeDeliveryStatus)(0),                       // 3: chatto.api.v1.NativeDeliveryStatus
	(*GetNativeNotificationConfigRequest)(nil),      // 4: chatto.api.v1.GetNativeNotificationConfigRequest
	(*GetNativeNotificationConfigResponse)(nil),     // 5: chatto.api.v1.GetNativeNotificationConfigResponse
	(*EnrollManagedFCMRequest)(nil),                 // 6: chatto.api.v1.EnrollManagedFCMRequest
	(*EnrollManagedFCMResponse)(nil),                // 7: chatto.api.v1.EnrollManagedFCMResponse
	(*NativeEndpointPreferences)(nil),               // 8: chatto.api.v1.NativeEndpointPreferences
	(*NativeEndpointPreferencesPatch)(nil),          // 9: chatto.api.v1.NativeEndpointPreferencesPatch
	(*NativeEndpoint)(nil),                          // 10: chatto.api.v1.NativeEndpoint
	(*RegisterNativeEndpointRequest)(nil),           // 11: chatto.api.v1.RegisterNativeEndpointRequest
	(*RegisterNativeEndpointResponse)(nil),          // 12: chatto.api.v1.RegisterNativeEndpointResponse
	(*RotateNativeEndpointRequest)(nil),             // 13: chatto.api.v1.RotateNativeEndpointRequest
	(*RotateNativeEndpointResponse)(nil),            // 14: chatto.api.v1.RotateNativeEndpointResponse
	(*UnregisterNativeEndpointRequest)(nil),         // 15: chatto.api.v1.UnregisterNativeEndpointRequest
	(*UnregisterNativeEndpointResponse)(nil),        // 16: chatto.api.v1.UnregisterNativeEndpointResponse
	(*ListNativeEndpointsRequest)(nil),              // 17: chatto.api.v1.ListNativeEndpointsRequest
	(*ListNativeEndpointsResponse)(nil),             // 18: chatto.api.v1.ListNativeEndpointsResponse
	(*UpdateNativeEndpointPreferencesRequest)(nil),  // 19: chatto.api.v1.UpdateNativeEndpointPreferencesRequest
	(*UpdateNativeEndpointPreferencesResponse)(nil), // 20: chatto.api.v1.UpdateNativeEndpointPreferencesResponse
	(*timestamppb.Timestamp)(nil),                   // 21: google.protobuf.Timestamp
}
var file_chatto_api_v1_native_notifications_proto_depIdxs = []int32{
	0,  // 0: chatto.api.v1.NativeEndpoint.platform:type_name -> chatto.api.v1.NativeNotificationPlatform
	1,  // 1: chatto.api.v1.NativeEndpoint.transport:type_name -> chatto.api.v1.NativeNotificationTransport
	21, // 2: chatto.api.v1.NativeEndpoint.created_at:type_name -> google.protobuf.Timestamp
	21, // 3: chatto.api.v1.NativeEndpoint.last_seen_at:type_name -> google.protobuf.Timestamp
	21, // 4: chatto.api.v1.NativeEndpoint.disabled_at:type_name -> google.protobuf.Timestamp
	2,  // 5: chatto.api.v1.NativeEndpoint.state:type_name -> chatto.api.v1.NativeEndpointState
	3,  // 6: chatto.api.v1.NativeEndpoint.last_delivery_status:type_name -> chatto.api.v1.NativeDeliveryStatus
	8,  // 7: chatto.api.v1.NativeEndpoint.preferences:type_name -> chatto.api.v1.NativeEndpointPreferences
	0,  // 8: chatto.api.v1.RegisterNativeEndpointRequest.platform:type_name -> chatto.api.v1.NativeNotificationPlatform
	1,  // 9: chatto.api.v1.RegisterNativeEndpointRequest.transport:type_name -> chatto.api.v1.NativeNotificationTransport
	9,  // 10: chatto.api.v1.RegisterNativeEndpointRequest.preferences:type_name -> chatto.api.v1.NativeEndpointPreferencesPatch
	10, // 11: chatto.api.v1.RegisterNativeEndpointResponse.endpoint:type_name -> chatto.api.v1.NativeEndpoint
	10, // 12: chatto.api.v1.RotateNativeEndpointResponse.endpoint:type_name -> chatto.api.v1.NativeEndpoint
	10, // 13: chatto.api.v1.ListNativeEndpointsResponse.endpoints:type_name -> chatto.api.v1.NativeEndpoint
	9,  // 14: chatto.api.v1.UpdateNativeEndpointPreferencesRequest.preferences:type_name -> chatto.api.v1.NativeEndpointPreferencesPatch
	10, // 15: chatto.api.v1.UpdateNativeEndpointPreferencesResponse.endpoint:type_name -> chatto.api.v1.NativeEndpoint
	4,  // 16: chatto.api.v1.NativeNotificationService.GetNativeNotificationConfig:input_type -> chatto.api.v1.GetNativeNotificationConfigRequest
	6,  // 17: chatto.api.v1.NativeNotificationService.EnrollManagedFCM:input_type -> chatto.api.v1.EnrollManagedFCMRequest
	11, // 18: chatto.api.v1.NativeNotificationService.RegisterNativeEndpoint:input_type -> chatto.api.v1.RegisterNativeEndpointRequest
	13, // 19: chatto.api.v1.NativeNotificationService.RotateNativeEndpoint:input_type -> chatto.api.v1.RotateNativeEndpointRequest
	15, // 20: chatto.api.v1.NativeNotificationService.UnregisterNativeEndpoint:input_type -> chatto.api.v1.UnregisterNativeEndpointRequest
	17, // 21: chatto.api.v1.NativeNotificationService.ListNativeEndpoints:input_type -> chatto.api.v1.ListNativeEndpointsRequest
	19, // 22: chatto.api.v1.NativeNotificationService.UpdateNativeEndpointPreferences:input_type -> chatto.api.v1.UpdateNativeEndpointPreferencesRequest
	5,  // 23: chatto.api.v1.NativeNotificationService.GetNativeNotificationConfig:output_type -> chatto.api.v1.GetNativeNotificationConfigResponse
	7,  // 24: chatto.api.v1.NativeNotificationService.EnrollManagedFCM:output_type -> chatto.api.v1.EnrollManagedFCMResponse
	12, // 25: chatto.api.v1.NativeNotificationService.RegisterNativeEndpoint:output_type -> chatto.api.v1.RegisterNativeEndpointResponse
	14, // 26: chatto.api.v1.NativeNotificationService.RotateNativeEndpoint:output_type -> chatto.api.v1.RotateNativeEndpointResponse
	16, // 27: chatto.api.v1.NativeNotificationService.UnregisterNativeEndpoint:output_type -> chatto.api.v1.UnregisterNativeEndpointResponse
	18, // 28: chatto.api.v1.NativeNotificationService.ListNativeEndpoints:output_type -> chatto.api.v1.ListNativeEndpointsResponse
	20, // 29: chatto.api.v1.NativeNotificationService.UpdateNativeEndpointPreferences:output_type -> chatto.api.v1.UpdateNativeEndpointPreferencesResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_chatto_api_v1_native_notifications_proto_init() }
func file_chatto_api_v1_native_notifications_proto_init() {
	if File_chatto_api_v1_native_notifications_proto != nil {
		return
	}
	file_chatto_api_v1_native_notifications_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_chatto_api_v1_native_notifications_proto_rawDesc), len(file_chatto_api_v1_native_notifications_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatto_api_v1_native_notifications_proto_goTypes,
		DependencyIndexes: file_chatto_api_v1_native_notifications_proto_depIdxs,
		EnumInfos:         file_chatto_api_v1_native_notifications_proto_enumTypes,
		MessageInfos:      file_chatto_api_v1_native_notifications_proto_msgTypes,
	}.Build()
	File_chatto_api_v1_native_notifications_proto = out.File
	file_chatto_api_v1_native_notifications_proto_goTypes = nil
	file_chatto_api_v1_native_notifications_proto_depIdxs = nil
}
